"""Snapshot the supported root namespace."""

import squid_reactivity


def test_public_api_snapshot() -> None:
    expected = {
        "ActionCommit",
        "ActionContext",
        "ActionContinuation",
        "ActionLedger",
        "ActionPurpose",
        "ActionResult",
        "ActionResultCodec",
        "ActionResultSnapshot",
        "ActionRollback",
        "ActionValidationError",
        "ActorRef",
        "Address",
        "CausalEventSnapshot",
        "CausalRef",
        "CellAddress",
        "CellPatch",
        "CellPatchSet",
        "CellReport",
        "ChangeReport",
        "CommitSequence",
        "ComputedReport",
        "ConditionalCellPatch",
        "ConflictDetail",
        "ContinuationFailureSnapshot",
        "DurableResultPolicy",
        "DurableResultSink",
        "ExceptionReport",
        "FrameworkIntegrityError",
        "FreshActionError",
        "KindKeyCodec",
        "LocalTopicBus",
        "Observation",
        "ObservedRead",
        "OperationEventSnapshot",
        "ReactiveConflictError",
        "ReactiveCycleError",
        "ReactiveWriteError",
        "ReactivityError",
        "RedactionPolicy",
        "ResourceEventSnapshot",
        "RollbackReason",
        "SharedState",
        "SharedStateFactory",
        "SharedStatePool",
        "StaleReactiveContextError",
        "StateOwner",
        "SubscriptionReconciler",
        "Topic",
        "TopicBus",
        "TopicCodec",
        "TransactionContribution",
        "TransactionParticipant",
        "TransactionView",
        "UndeclaredStateError",
        "action_scope",
        "action_result_sink",
        "add_action_result_sink",
        "addresses",
        "apply_conditional_patches",
        "apply_local_overwrite_patches",
        "batch",
        "block_writes",
        "computed",
        "current_action",
        "enlist",
        "export_state",
        "fresh_action_transaction",
        "inspect_cells",
        "inspect_computed",
        "observe_reads",
        "on_action_commit",
        "on_action_result",
        "on_action_rollback",
        "readonly_transaction",
        "relaxed_read",
        "remove_action_result_sink",
        "restore_state",
        "state",
        "strong_read",
        "transaction",
        "untracked",
        "watch",
    }
    assert set(squid_reactivity.__all__) == expected
    assert all(hasattr(squid_reactivity, name) for name in expected)
