"""Semantic-first, limits-aware UI planning and component runtime."""

from importlib import import_module

from squid_layouts import (
    errors,
    forms,
    guards,
    html,
    interactions,
    patterns,
    planning,
    primitives,
    profiling,
    routing,
    runtime,
    resources,
    scene,
    semantic,
    sources,
    temporal,
    text,
)

# chrome, emoji, and entity carry no ROOT_API names of their own but stay reachable as
# sl.chrome.X etc, deeper-tier escape hatches: the namespace bundle above transitively
# imports each of them (runtime -> histories -> chrome, primitives -> emoji, semantic ->
# entity), which is what binds them as attributes of this package. document and palette get
# the same binding as a side effect of the Document/Palette imports below. Nothing here
# imports any of the five directly, on purpose: chrome.py itself needs
# squid_layouts.runtime.context, so an eager `import chrome` placed ahead of the namespace
# bundle (which ruff's isort would do, being alphabetical) resurrects the exact partial-init
# cycle this transitive order avoids.
from squid_layouts.document import (
    Document,
    DocumentLike,
)
from squid_layouts.factories import (
    ChildLike,
    Conditional,
    TextValue,
    action,
    action_group,
    actions,
    article,
    aside,
    block,
    bullet,
    bullets,
    choice,
    choices,
    cluster,
    code,
    column,
    columns,
    controlled,
    destination,
    details,
    download,
    entities,
    entity_choice,
    field,
    fields,
    figure,
    form,
    group,
    heading,
    item,
    item_label,
    items,
    link,
    managed,
    measure,
    media,
    media_item,
    navigation,
    note,
    paragraph,
    progress,
    quote,
    rating,
    routed_action,
    routed_choices,
    section,
    stack,
    status,
    summary,
    table,
    table_row,
    themed,
    timestamp,
    toggle,
    zoned_timestamp,
)
from squid_layouts.interactions import (
    ActionEvent,
    EntitySelectionEvent,
    PressEvent,
    SelectionEvent,
    SubmitEvent,
)
from squid_layouts.palette import Palette
from squid_layouts.runtime.component import Component
from squid_layouts.runtime.context import ContextKey
from squid_layouts.runtime.reactivity import (
    computed,
    state,
)
from squid_layouts.runtime.resources import resource
from squid_layouts.semantic import (
    ChoiceEvent,
    EntityEvent,
    LayoutNode,
    NavigateEvent,
    OpenEvent,
    ScaleEvent,
    ToggleEvent,
    Tone,
    best_effort,
    budget,
    fallback,
    keep_with_next,
    optional,
    paged,
    spill,
    truncate,
    unbreakable,
)
from squid_layouts.text import (
    TextLike,
    md,
    plain,
    raw_md,
)


def __getattr__(name: str) -> object:
    if name == "discord":
        return import_module("squid_layouts.discord")
    raise AttributeError(name)


__all__ = [
    "ActionEvent",
    "ChildLike",
    "ChoiceEvent",
    "Component",
    "Conditional",
    "ContextKey",
    "Document",
    "DocumentLike",
    "EntityEvent",
    "EntitySelectionEvent",
    "LayoutNode",
    "NavigateEvent",
    "OpenEvent",
    "Palette",
    "PressEvent",
    "ScaleEvent",
    "SelectionEvent",
    "SubmitEvent",
    "TextLike",
    "TextValue",
    "ToggleEvent",
    "Tone",
    "action",
    "action_group",
    "actions",
    "article",
    "aside",
    "best_effort",
    "block",
    "budget",
    "bullet",
    "bullets",
    "choice",
    "choices",
    "cluster",
    "code",
    "column",
    "columns",
    "computed",
    "controlled",
    "destination",
    "details",
    "download",
    "entities",
    "entity_choice",
    "errors",
    "fallback",
    "field",
    "fields",
    "figure",
    "form",
    "forms",
    "group",
    "guards",
    "heading",
    "html",
    "interactions",
    "item",
    "item_label",
    "items",
    "keep_with_next",
    "link",
    "managed",
    "md",
    "measure",
    "media",
    "media_item",
    "navigation",
    "note",
    "optional",
    "paged",
    "paragraph",
    "patterns",
    "plain",
    "planning",
    "primitives",
    "profiling",
    "progress",
    "quote",
    "rating",
    "raw_md",
    "resource",
    "resources",
    "routed_action",
    "routed_choices",
    "routing",
    "runtime",
    "scene",
    "section",
    "semantic",
    "sources",
    "spill",
    "stack",
    "state",
    "status",
    "summary",
    "table",
    "table_row",
    "temporal",
    "text",
    "themed",
    "timestamp",
    "toggle",
    "truncate",
    "unbreakable",
    "zoned_timestamp",
]
