"""Semantic-first, limits-aware UI planning and component runtime."""

from importlib import import_module

from squid_layouts import html, planning, primitives, runtime, scene, semantic
from squid_layouts.actions import (
    ActionEvent,
    ActionPolicy,
    ActionResponder,
    Actor,
    PressEvent,
    SelectionEvent,
    SubmitEvent,
    Visibility,
)
from squid_layouts.chrome import DEFAULT_CHROME, Chrome
from squid_layouts.document import Asset, Document, InlineAsset, StoredAsset, as_document
from squid_layouts.errors import (
    DrawInvariantError,
    LayoutDegradedError,
    LayoutError,
    LayoutInvariantError,
    UnsolvableLayoutError,
)
from squid_layouts.planning.planner import plan
from squid_layouts.runtime.component import Component
from squid_layouts.runtime.context import ContextKey
from squid_layouts.runtime.reactivity import ReactiveWriteError, batch, computed, state, transaction
from squid_layouts.scene.model import PlanEvent, PlanMetrics, PlanReport, PlanResult, SceneDocument
from squid_layouts.semantic import (
    Action,
    ActionDisplay,
    ActionGroup,
    Actions,
    Adaptation,
    Article,
    Aside,
    BestEffort,
    Choice,
    ChoiceEvent,
    Choices,
    Cluster,
    Code,
    Column,
    Destination,
    DetailLevel,
    Details,
    Emphasis,
    FallbackContent,
    Field,
    Fields,
    Figure,
    Flexibility,
    Group,
    Heading,
    Importance,
    Item,
    ItemDisplay,
    Items,
    LayoutNode,
    Link,
    List,
    ListItem,
    Measure,
    Media,
    MediaDisplay,
    MediaItem,
    NavigateEvent,
    Navigation,
    NavigationDisplay,
    OptionalContent,
    Paragraph,
    Progress,
    Quote,
    Section,
    SemanticNode,
    Spilled,
    Stack,
    Status,
    Table,
    TableDisplay,
    TableRow,
    Tone,
    Truncated,
    best_effort,
    fallback,
    optional,
    spill,
    truncate,
)
from squid_layouts.text import RawMarkdown, ResolvedText, TextDialect, md, plain, raw_md


def __getattr__(name: str) -> object:
    if name == "discord":
        return import_module("squid_layouts.discord")
    raise AttributeError(name)


__all__ = [
    "DEFAULT_CHROME",
    "Action",
    "ActionDisplay",
    "ActionEvent",
    "ActionGroup",
    "ActionPolicy",
    "ActionResponder",
    "Actions",
    "Actor",
    "Adaptation",
    "Article",
    "Aside",
    "Asset",
    "BestEffort",
    "Choice",
    "ChoiceEvent",
    "Choices",
    "Chrome",
    "Cluster",
    "Code",
    "Column",
    "Component",
    "ContextKey",
    "Destination",
    "DetailLevel",
    "Details",
    "Document",
    "DrawInvariantError",
    "Emphasis",
    "FallbackContent",
    "Field",
    "Fields",
    "Figure",
    "Flexibility",
    "Group",
    "Heading",
    "Importance",
    "InlineAsset",
    "Item",
    "ItemDisplay",
    "Items",
    "LayoutDegradedError",
    "LayoutError",
    "LayoutInvariantError",
    "LayoutNode",
    "Link",
    "List",
    "ListItem",
    "Measure",
    "Media",
    "MediaDisplay",
    "MediaItem",
    "NavigateEvent",
    "Navigation",
    "NavigationDisplay",
    "OptionalContent",
    "Paragraph",
    "PlanEvent",
    "PlanMetrics",
    "PlanReport",
    "PlanResult",
    "PressEvent",
    "Progress",
    "Quote",
    "RawMarkdown",
    "ReactiveWriteError",
    "ResolvedText",
    "SceneDocument",
    "Section",
    "SelectionEvent",
    "SemanticNode",
    "Spilled",
    "Stack",
    "Status",
    "StoredAsset",
    "SubmitEvent",
    "Table",
    "TableDisplay",
    "TableRow",
    "TextDialect",
    "Tone",
    "Truncated",
    "UnsolvableLayoutError",
    "Visibility",
    "as_document",
    "batch",
    "best_effort",
    "computed",
    "fallback",
    "html",
    "md",
    "optional",
    "plain",
    "plan",
    "planning",
    "primitives",
    "raw_md",
    "runtime",
    "scene",
    "semantic",
    "spill",
    "state",
    "transaction",
    "truncate",
]
