"""Public account domain API: one account, many identities."""

from squid.accounts.domain.models import (
    CONSENT_CUTOFF,
    CURRENT_CONSENT_VERSION,
    MERGE_PROOF_MAX_AGE_SECONDS,
    Account,
    AccountConsent,
    AccountIdentity,
    AccountMerge,
    AliasClaim,
    ClaimMethod,
    ClaimStatus,
    CreatorAlias,
    CreatorProfile,
    IdentityProvider,
    IdentityRefresh,
    RecentAccountProof,
    VerificationCode,
    fold_creator_name,
)

__all__ = [
    "CONSENT_CUTOFF",
    "CURRENT_CONSENT_VERSION",
    "MERGE_PROOF_MAX_AGE_SECONDS",
    "Account",
    "AccountConsent",
    "AccountIdentity",
    "AccountMerge",
    "AliasClaim",
    "ClaimMethod",
    "ClaimStatus",
    "CreatorAlias",
    "CreatorProfile",
    "IdentityProvider",
    "IdentityRefresh",
    "RecentAccountProof",
    "VerificationCode",
    "fold_creator_name",
]
