insert into server_settings(server_id, smallest_channel_id, fastest_channel_id, first_channel_id, builds_channel_id, voting_channel_id, in_server)
values
(433618741528625152, 536004554743873556, 536004554743873556, 536004554743873556, 536004554743873556, 536004554743873556, TRUE);

-- Door patterns (formerly the `types` table, now official pattern tags)
with inserted_patterns as (
    insert into tag_definitions (stable_key, display_name, normalized_name, authority, semantic_kind, value_type, render_template, default_display_order, moderation_status)
    values
    ('regular', 'Regular', 'regular', 'official', 'pattern', 'none', '{name}', 1, 'approved'),
    ('funnel', 'Funnel', 'funnel', 'official', 'pattern', 'none', '{name}', 2, 'approved'),
    ('asdjke', 'Asdjke', 'asdjke', 'official', 'pattern', 'none', '{name}', 3, 'approved'),
    ('cave', 'Cave', 'cave', 'official', 'pattern', 'none', '{name}', 4, 'approved'),
    ('corner', 'Corner', 'corner', 'official', 'pattern', 'none', '{name}', 5, 'approved'),
    ('dual_cave_corner', 'Dual Cave Corner', 'dual cave corner', 'official', 'pattern', 'none', '{name}', 6, 'approved'),
    ('staircase', 'Staircase', 'staircase', 'official', 'pattern', 'none', '{name}', 7, 'approved'),
    ('gold_play_button', 'Gold Play Button', 'gold play button', 'official', 'pattern', 'none', '{name}', 8, 'approved'),
    ('vortex', 'Vortex', 'vortex', 'official', 'pattern', 'none', '{name}', 9, 'approved'),
    ('pitch', 'Pitch', 'pitch', 'official', 'pattern', 'none', '{name}', 10, 'approved'),
    ('bar', 'Bar', 'bar', 'official', 'pattern', 'none', '{name}', 11, 'approved'),
    ('vertical', 'Vertical', 'vertical', 'official', 'pattern', 'none', '{name}', 12, 'approved'),
    ('yaw', 'Yaw', 'yaw', 'official', 'pattern', 'none', '{name}', 13, 'approved'),
    ('reversed', 'Reversed', 'reversed', 'official', 'pattern', 'none', '{name}', 14, 'approved'),
    ('inverted', 'Inverted', 'inverted', 'official', 'pattern', 'none', '{name}', 15, 'approved'),
    ('dual', 'Dual', 'dual', 'official', 'pattern', 'none', '{name}', 16, 'approved'),
    ('vault', 'Vault', 'vault', 'official', 'pattern', 'none', '{name}', 17, 'approved'),
    ('iris', 'Iris', 'iris', 'official', 'pattern', 'none', '{name}', 18, 'approved'),
    ('onion', 'Onion', 'onion', 'official', 'pattern', 'none', '{name}', 19, 'approved'),
    ('stargate', 'Stargate', 'stargate', 'official', 'pattern', 'none', '{name}', 20, 'approved'),
    ('full_lamp', 'Full Lamp', 'full lamp', 'official', 'pattern', 'none', '{name}', 21, 'approved'),
    ('lamp', 'Lamp', 'lamp', 'official', 'pattern', 'none', '{name}', 22, 'approved'),
    ('hidden_lamp', 'Hidden Lamp', 'hidden lamp', 'official', 'pattern', 'none', '{name}', 23, 'approved'),
    ('sissy_bar', 'Sissy Bar', 'sissy bar', 'official', 'pattern', 'none', '{name}', 24, 'approved'),
    ('checkerboard', 'Checkerboard', 'checkerboard', 'official', 'pattern', 'none', '{name}', 25, 'approved'),
    ('windows', 'Windows', 'windows', 'official', 'pattern', 'none', '{name}', 26, 'approved'),
    ('redstone_block_center', 'Redstone Block Center', 'redstone block center', 'official', 'pattern', 'none', '{name}', 27, 'approved'),
    ('sand', 'Sand', 'sand', 'official', 'pattern', 'none', '{name}', 28, 'approved'),
    ('glass_stripe', 'Glass Stripe', 'glass stripe', 'official', 'pattern', 'none', '{name}', 29, 'approved'),
    ('center_glass', 'Center Glass', 'center glass', 'official', 'pattern', 'none', '{name}', 30, 'approved'),
    ('always_on_lamp', 'Always On Lamp', 'always on lamp', 'official', 'pattern', 'none', '{name}', 31, 'approved'),
    ('circle', 'Circle', 'circle', 'official', 'pattern', 'none', '{name}', 32, 'approved'),
    ('triangle', 'Triangle', 'triangle', 'official', 'pattern', 'none', '{name}', 33, 'approved'),
    ('right_triangle', 'Right Triangle', 'right triangle', 'official', 'pattern', 'none', '{name}', 34, 'approved'),
    ('banana', 'Banana', 'banana', 'official', 'pattern', 'none', '{name}', 35, 'approved'),
    ('diamond', 'Diamond', 'diamond', 'official', 'pattern', 'none', '{name}', 36, 'approved'),
    ('slab_shifted', 'Slab-Shifted', 'slab-shifted', 'official', 'pattern', 'none', '{name}', 37, 'approved'),
    ('rail', 'Rail', 'rail', 'official', 'pattern', 'none', '{name}', 38, 'approved'),
    ('dual_rail', 'Dual Rail', 'dual rail', 'official', 'pattern', 'none', '{name}', 39, 'approved'),
    ('carpet', 'Carpet', 'carpet', 'official', 'pattern', 'none', '{name}', 40, 'approved'),
    ('semi_tnt', 'Semi TNT', 'semi tnt', 'official', 'pattern', 'none', '{name}', 41, 'approved'),
    ('full_tnt', 'Full TNT', 'full tnt', 'official', 'pattern', 'none', '{name}', 42, 'approved')
    returning id
)
insert into tag_applicabilities (tag_id, build_kind)
select id, 'Door' from inserted_patterns;

-- Door restrictions (formerly the `restrictions` table, now official restriction tags)
with inserted_restrictions as (
    insert into tag_definitions (stable_key, display_name, normalized_name, authority, semantic_kind, restriction_type, value_type, record_operator, render_template, default_display_order, moderation_status)
    values
    ('super_seamless', 'Super Seamless', 'super seamless', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 1, 'approved'),
    ('full_seamless', 'Full Seamless', 'full seamless', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 2, 'approved'),
    ('semi_seamless', 'Semi Seamless', 'semi seamless', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 3, 'approved'),
    ('quart_seamless', 'Quart Seamless', 'quart seamless', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 4, 'approved'),
    ('dentless', 'Dentless', 'dentless', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 5, 'approved'),
    ('full_trapdoor', 'Full Trapdoor', 'full trapdoor', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 6, 'approved'),
    ('flush', 'Flush', 'flush', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 7, 'approved'),
    ('deluxe', 'Deluxe', 'deluxe', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 8, 'approved'),
    ('flush_layout', 'Flush Layout', 'flush layout', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 9, 'approved'),
    ('semi_flush', 'Semi Flush', 'semi flush', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 10, 'approved'),
    ('semi_deluxe', 'Semi Deluxe', 'semi deluxe', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 11, 'approved'),
    ('full_floor_hipster', 'Full Floor Hipster', 'full floor hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 12, 'approved'),
    ('full_ceiling_hipster', 'Full Ceiling Hipster', 'full ceiling hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 13, 'approved'),
    ('full_wall_hipster', 'Full Wall Hipster', 'full wall hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 14, 'approved'),
    ('semi_floor_hipster', 'Semi Floor Hipster', 'semi floor hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 15, 'approved'),
    ('semi_ceiling_hipster', 'Semi Ceiling Hipster', 'semi ceiling hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 16, 'approved'),
    ('semi_wall_hipster', 'Semi Wall Hipster', 'semi wall hipster', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 17, 'approved'),
    ('expandable', 'Expandable', 'expandable', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 18, 'approved'),
    ('full_tileable', 'Full Tileable', 'full tileable', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 19, 'approved'),
    ('semi_tileable', 'Semi Tileable', 'semi tileable', 'official', 'restriction', 'wiring-placement', 'none', 'present', '{name}', 20, 'approved'),
    ('no_slime_blocks', 'No Slime Blocks', 'no slime blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 21, 'approved'),
    ('no_honey_blocks', 'No Honey Blocks', 'no honey blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 22, 'approved'),
    ('no_gravity_blocks', 'No Gravity Blocks', 'no gravity blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 23, 'approved'),
    ('no_sticky_pistons', 'No Sticky Pistons', 'no sticky pistons', 'official', 'restriction', 'component', 'none', 'present', '{name}', 24, 'approved'),
    ('contained_slime_blocks', 'Contained Slime Blocks', 'contained slime blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 25, 'approved'),
    ('contained_honey_blocks', 'Contained Honey Blocks', 'contained honey blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 26, 'approved'),
    ('only_wiring_slime_blocks', 'Only Wiring Slime Blocks', 'only wiring slime blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 27, 'approved'),
    ('only_wiring_honey_blocks', 'Only Wiring Honey Blocks', 'only wiring honey blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 28, 'approved'),
    ('only_wiring_gravity_blocks', 'Only Wiring Gravity Blocks', 'only wiring gravity blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 29, 'approved'),
    ('no_observers', 'No Observers', 'no observers', 'official', 'restriction', 'component', 'none', 'present', '{name}', 30, 'approved'),
    ('no_note_blocks', 'No Note Blocks', 'no note blocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 31, 'approved'),
    ('no_clocks', 'No Clocks', 'no clocks', 'official', 'restriction', 'component', 'none', 'present', '{name}', 32, 'approved'),
    ('no_entities', 'No Entities', 'no entities', 'official', 'restriction', 'component', 'none', 'present', '{name}', 33, 'approved'),
    ('no_flying_machines', 'No Flying Machines', 'no flying machines', 'official', 'restriction', 'component', 'none', 'present', '{name}', 34, 'approved'),
    ('zomba', 'Zomba', 'zomba', 'official', 'restriction', 'component', 'none', 'present', '{name}', 35, 'approved'),
    ('zombi', 'Zombi', 'zombi', 'official', 'restriction', 'component', 'none', 'present', '{name}', 36, 'approved'),
    ('torch_and_dust_only', 'Torch and Dust Only', 'torch and dust only', 'official', 'restriction', 'component', 'none', 'present', '{name}', 37, 'approved'),
    ('redstone_block_only', 'Redstone Block Only', 'redstone block only', 'official', 'restriction', 'component', 'none', 'present', '{name}', 38, 'approved'),
    ('not_locational', 'Not Locational', 'not locational', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 39, 'approved'),
    ('not_directional', 'Not Directional', 'not directional', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 40, 'approved'),
    ('locational_with_fixes', 'Locational With Fixes', 'locational with fixes', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 41, 'approved'),
    ('directional_with_fixes', 'Directional With Fixes', 'directional with fixes', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 42, 'approved'),
    ('locational', 'Locational', 'locational', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 43, 'approved'),
    ('directional', 'Directional', 'directional', 'official', 'restriction', 'miscellaneous', 'none', 'present', '{name}', 44, 'approved')
    returning id
)
insert into tag_applicabilities (tag_id, build_kind)
select id, 'Door' from inserted_restrictions;

insert into versions (edition, major_version, minor_version, patch_number)
values
('Java', 1, 20, 5),
('Java', 1, 20, 4),
('Java', 1, 20, 3),
('Java', 1, 20, 2),
('Java', 1, 20, 1),
('Java', 1, 20, 0),
('Java', 1, 19, 4),
('Java', 1, 19, 3),
('Java', 1, 19, 2),
('Java', 1, 19, 1),
('Java', 1, 19, 0),
('Java', 1, 18, 2),
('Java', 1, 18, 1),
('Java', 1, 18, 0),
('Java', 1, 17, 1),
('Java', 1, 17, 0),
('Java', 1, 16, 5),
('Java', 1, 16, 4),
('Java', 1, 16, 3),
('Java', 1, 16, 2),
('Java', 1, 16, 1),
('Java', 1, 16, 0),
('Java', 1, 15, 2),
('Java', 1, 15, 1),
('Java', 1, 15, 0),
('Java', 1, 14, 4),
('Java', 1, 14, 3),
('Java', 1, 14, 2),
('Java', 1, 14, 1),
('Java', 1, 14, 0),
('Java', 1, 13, 2),
('Java', 1, 13, 1),
('Java', 1, 13, 0),
('Java', 1, 12, 2),
('Java', 1, 12, 1),
('Java', 1, 12, 0),
('Java', 1, 11, 2),
('Java', 1, 11, 1),
('Java', 1, 11, 0),
('Java', 1, 10, 2),
('Java', 1, 10, 1),
('Java', 1, 10, 0),
('Java', 1, 9, 4),
('Java', 1, 9, 3),
('Java', 1, 9, 2),
('Java', 1, 9, 1),
('Java', 1, 9, 0),
('Java', 1, 8, 9),
('Java', 1, 8, 8),
('Java', 1, 8, 7),
('Java', 1, 8, 6),
('Java', 1, 8, 5),
('Java', 1, 8, 4),
('Java', 1, 8, 3),
('Java', 1, 8, 2),
('Java', 1, 8, 1),
('Java', 1, 8, 0),
('Java', 1, 7, 10),
('Java', 1, 7, 9),
('Java', 1, 7, 8),
('Java', 1, 7, 7),
('Java', 1, 7, 6),
('Java', 1, 7, 5),
('Java', 1, 7, 4),
('Java', 1, 7, 2),
('Java', 1, 6, 4),
('Java', 1, 6, 2),
('Java', 1, 6, 1),
('Java', 1, 5, 2),
('Java', 1, 5, 1),
('Java', 1, 5, 0),
('Java', 1, 4, 7),
('Java', 1, 4, 6),
('Java', 1, 4, 5),
('Java', 1, 4, 4),
('Java', 1, 4, 2),
('Java', 1, 3, 2),
('Java', 1, 3, 1),
('Java', 1, 2, 5),
('Java', 1, 2, 4),
('Java', 1, 2, 3),
('Java', 1, 2, 2),
('Java', 1, 2, 1),
('Java', 1, 1, 0),
('Java', 1, 0, 1),
('Java', 1, 0, 0),
('Bedrock', 1, 20, 80),
('Bedrock', 1, 20, 73),
('Bedrock', 1, 20, 72),
('Bedrock', 1, 20, 71),
('Bedrock', 1, 20, 70),
('Bedrock', 1, 20, 62),
('Bedrock', 1, 20, 60),
('Bedrock', 1, 20, 51),
('Bedrock', 1, 20, 50),
('Bedrock', 1, 20, 41),
('Bedrock', 1, 20, 40),
('Bedrock', 1, 20, 32),
('Bedrock', 1, 20, 31),
('Bedrock', 1, 20, 30),
('Bedrock', 1, 20, 15),
('Bedrock', 1, 20, 14),
('Bedrock', 1, 20, 13),
('Bedrock', 1, 20, 12),
('Bedrock', 1, 20, 10),
('Bedrock', 1, 20, 1),
('Bedrock', 1, 20, 0),
('Bedrock', 1, 19, 83),
('Bedrock', 1, 19, 81),
('Bedrock', 1, 19, 80),
('Bedrock', 1, 19, 73),
('Bedrock', 1, 19, 72),
('Bedrock', 1, 19, 71),
('Bedrock', 1, 19, 70),
('Bedrock', 1, 19, 63),
('Bedrock', 1, 19, 62),
('Bedrock', 1, 19, 60),
('Bedrock', 1, 19, 51),
('Bedrock', 1, 19, 50),
('Bedrock', 1, 19, 41),
('Bedrock', 1, 19, 40),
('Bedrock', 1, 19, 31),
('Bedrock', 1, 19, 30),
('Bedrock', 1, 19, 22),
('Bedrock', 1, 19, 21),
('Bedrock', 1, 19, 20),
('Bedrock', 1, 19, 11),
('Bedrock', 1, 19, 10),
('Bedrock', 1, 19, 2),
('Bedrock', 1, 19, 0),
('Bedrock', 1, 18, 33),
('Bedrock', 1, 18, 32),
('Bedrock', 1, 18, 31),
('Bedrock', 1, 18, 30),
('Bedrock', 1, 18, 12),
('Bedrock', 1, 18, 11),
('Bedrock', 1, 18, 10),
('Bedrock', 1, 18, 2),
('Bedrock', 1, 18, 1),
('Bedrock', 1, 18, 0),
('Bedrock', 1, 17, 41),
('Bedrock', 1, 17, 40),
('Bedrock', 1, 17, 34),
('Bedrock', 1, 17, 33),
('Bedrock', 1, 17, 32),
('Bedrock', 1, 17, 30),
('Bedrock', 1, 17, 11),
('Bedrock', 1, 17, 10),
('Bedrock', 1, 17, 2),
('Bedrock', 1, 17, 1),
('Bedrock', 1, 17, 0),
('Bedrock', 1, 16, 221),
('Bedrock', 1, 16, 220),
('Bedrock', 1, 16, 210),
('Bedrock', 1, 16, 201),
('Bedrock', 1, 16, 200),
('Bedrock', 1, 16, 101),
('Bedrock', 1, 16, 100),
('Bedrock', 1, 16, 61),
('Bedrock', 1, 16, 60),
('Bedrock', 1, 16, 50),
('Bedrock', 1, 16, 42),
('Bedrock', 1, 16, 40),
('Bedrock', 1, 16, 21),
('Bedrock', 1, 16, 20),
('Bedrock', 1, 16, 10),
('Bedrock', 1, 16, 1),
('Bedrock', 1, 16, 0),
('Bedrock', 1, 14, 60),
('Bedrock', 1, 14, 41),
('Bedrock', 1, 14, 30),
('Bedrock', 1, 14, 21),
('Bedrock', 1, 14, 20),
('Bedrock', 1, 14, 1),
('Bedrock', 1, 14, 0),
('Bedrock', 1, 14, 0),
('Bedrock', 1, 13, 3),
('Bedrock', 1, 13, 2),
('Bedrock', 1, 13, 1),
('Bedrock', 1, 13, 0),
('Bedrock', 1, 12, 1),
('Bedrock', 1, 12, 0),
('Bedrock', 1, 11, 4),
('Bedrock', 1, 11, 3),
('Bedrock', 1, 11, 2),
('Bedrock', 1, 11, 1),
('Bedrock', 1, 11, 0),
('Bedrock', 1, 10, 1),
('Bedrock', 1, 10, 0),
('Bedrock', 1, 9, 0),
('Bedrock', 1, 8, 1),
('Bedrock', 1, 8, 0),
('Bedrock', 1, 7, 1),
('Bedrock', 1, 7, 0),
('Bedrock', 1, 6, 2),
('Bedrock', 1, 6, 1),
('Bedrock', 1, 6, 0),
('Bedrock', 1, 5, 3),
('Bedrock', 1, 5, 2),
('Bedrock', 1, 5, 1),
('Bedrock', 1, 5, 0),
('Bedrock', 1, 4, 4),
('Bedrock', 1, 4, 3),
('Bedrock', 1, 4, 2),
('Bedrock', 1, 4, 1),
('Bedrock', 1, 4, 0),
('Bedrock', 1, 2, 16),
('Bedrock', 1, 2, 15),
('Bedrock', 1, 2, 14),
('Bedrock', 1, 2, 13),
('Bedrock', 1, 2, 11),
('Bedrock', 1, 2, 10),
('Bedrock', 1, 2, 9),
('Bedrock', 1, 2, 8),
('Bedrock', 1, 2, 7),
('Bedrock', 1, 2, 6),
('Bedrock', 1, 2, 6),
('Bedrock', 1, 2, 5),
('Bedrock', 1, 2, 3),
('Bedrock', 1, 2, 2),
('Bedrock', 1, 2, 1),
('Bedrock', 1, 2, 0);
