"""Re-exports `squid_reactivity`'s actions and core under `squid_ui.runtime`; nothing here is defined by `squid_ui`.

The underscored names (`_CURRENT`, `_Cell`, `_State`, `_Transaction`) are `squid_reactivity.internals`
for tests that poke at the transaction in flight; they are not API.
"""

from squid_reactivity.actions import (
    ActionCommit,
    ActionContext,
    ActionContinuation,
    ActionLedger,
    ActionPurpose,
    ActionResult,
    ActionRollback,
    RollbackReason,
)
from squid_reactivity.core import (
    CellPatch,
    CellPatchSet,
    CellReport,
    ComputedReport,
    ConditionalCellPatch,
    FrameworkIntegrityError,
    FreshActionError,
    Observation,
    ReactiveConflictError,
    ReactiveCycleError,
    ReactiveWriteError,
    StaleReactiveContextError,
    StateOwner,
    TransactionParticipant,
    TransactionView,
    UndeclaredStateError,
    addresses,
    apply_conditional_patches,
    apply_local_overwrite_patches,
    batch,
    block_writes,
    computed,
    enlist,
    export_state,
    fresh_action_transaction,
    has_action_hook,
    inspect_cells,
    inspect_computed,
    observe_reads,
    on_action_commit,
    on_action_result,
    on_action_rollback,
    readonly_transaction,
    relaxed_read,
    restore_state,
    state,
    strong_read,
    transaction,
    untracked,
)
from squid_reactivity.internals import CURRENT_TRANSACTION as _CURRENT
from squid_reactivity.internals import Cell as _Cell
from squid_reactivity.internals import StateDescriptor as _State
from squid_reactivity.internals import Transaction as _Transaction

__all__ = [
    "_CURRENT",
    "ActionCommit",
    "ActionContext",
    "ActionContinuation",
    "ActionLedger",
    "ActionPurpose",
    "ActionResult",
    "ActionRollback",
    "CellPatch",
    "CellPatchSet",
    "CellReport",
    "ComputedReport",
    "ConditionalCellPatch",
    "FrameworkIntegrityError",
    "FreshActionError",
    "Observation",
    "ReactiveConflictError",
    "ReactiveCycleError",
    "ReactiveWriteError",
    "RollbackReason",
    "StaleReactiveContextError",
    "StateOwner",
    "TransactionParticipant",
    "TransactionView",
    "UndeclaredStateError",
    "_Cell",
    "_State",
    "_Transaction",
    "addresses",
    "apply_conditional_patches",
    "apply_local_overwrite_patches",
    "batch",
    "block_writes",
    "computed",
    "enlist",
    "export_state",
    "fresh_action_transaction",
    "has_action_hook",
    "inspect_cells",
    "inspect_computed",
    "observe_reads",
    "on_action_commit",
    "on_action_result",
    "on_action_rollback",
    "readonly_transaction",
    "relaxed_read",
    "restore_state",
    "state",
    "strong_read",
    "transaction",
    "untracked",
]
