"""Frontend-neutral component runtime and presentation state."""

from squid_layouts.runtime.component import Component
from squid_layouts.runtime.context import ContextKey
from squid_layouts.runtime.histories import (
    CompensationExecution,
    CompensationSpec,
    CompensationStatus,
    History,
    HistoryEntry,
    HistoryEntrySnapshot,
    HistoryEntryState,
    HistoryError,
    HistoryResult,
    HistoryResultStatus,
    HistorySnapshot,
    RedoResult,
    UndoPlan,
    UndoResult,
    history,
    history_actions,
    inspect_histories,
)
from squid_layouts.runtime.presentation import (
    ActivePagers,
    CursorState,
    CursorUpdate,
    DisclosureState,
    PresentationSession,
    SelectionState,
    SessionUpdate,
    StrategyState,
    StrategyUpdate,
    ToggleState,
    ToggleUpdate,
    apply_updates,
)
from squid_layouts.runtime.reactivity import (
    ActionCommit,
    ActionContext,
    ActionKind,
    ActionLedger,
    ActionOutcome,
    ActionParticipant,
    ActionRollback,
    Aftermath,
    CellPatch,
    CellPatchSet,
    CellReport,
    ComputedReport,
    ConditionalCellPatch,
    Observation,
    ReactiveConflictError,
    ReactiveCycleError,
    ReactiveWriteError,
    RollbackReason,
    StaleReactiveContextError,
    TransactionView,
    UndeclaredStateError,
    addresses,
    apply_conditional_patches,
    batch,
    block_writes,
    computed,
    export_state,
    fresh_action_transaction,
    inspect_cells,
    inspect_computed,
    join_action,
    on_action_commit,
    on_action_outcome,
    on_action_rollback,
    relaxed_read,
    restore_state,
    state,
    transaction,
    untracked,
)
from squid_layouts.runtime.resources import (
    AtomicResource,
    AtomicResourceStatus,
    Failed,
    Pending,
    PendingPolicy,
    Ready,
    Resource,
    ResourceNotReadyError,
    ResourceStatus,
    resource,
)
from squid_layouts.runtime.shared import Shared, SharedFactory, SharedPool
from squid_layouts.runtime.topics import (
    Address,
    BusSnapshot,
    CellAddress,
    KindKeyCodec,
    LocalTopicBus,
    Subscriber,
    SubscriptionReconciler,
    Topic,
    TopicBus,
    TopicCodec,
    TopicSnapshot,
    watch,
)


def __getattr__(name: str):
    if name == "ComponentRuntime":
        from squid_layouts.runtime.owner import ComponentRuntime

        return ComponentRuntime
    raise AttributeError(name)


__all__ = [
    "ActionCommit",
    "ActionContext",
    "ActionKind",
    "ActionLedger",
    "ActionOutcome",
    "ActionParticipant",
    "ActionRollback",
    "ActivePagers",
    "Address",
    "Aftermath",
    "AtomicResource",
    "AtomicResourceStatus",
    "BusSnapshot",
    "CellAddress",
    "CellPatch",
    "CellPatchSet",
    "CellReport",
    "CompensationExecution",
    "CompensationSpec",
    "CompensationStatus",
    "Component",
    "ComponentRuntime",
    "ComputedReport",
    "ConditionalCellPatch",
    "ContextKey",
    "CursorState",
    "CursorUpdate",
    "DisclosureState",
    "Failed",
    "History",
    "HistoryEntry",
    "HistoryEntrySnapshot",
    "HistoryEntryState",
    "HistoryError",
    "HistoryResult",
    "HistoryResultStatus",
    "HistorySnapshot",
    "KindKeyCodec",
    "LocalTopicBus",
    "Observation",
    "Pending",
    "PendingPolicy",
    "PresentationSession",
    "ReactiveConflictError",
    "ReactiveCycleError",
    "ReactiveWriteError",
    "Ready",
    "RedoResult",
    "Resource",
    "ResourceNotReadyError",
    "ResourceStatus",
    "RollbackReason",
    "SelectionState",
    "SessionUpdate",
    "Shared",
    "SharedFactory",
    "SharedPool",
    "StaleReactiveContextError",
    "StrategyState",
    "StrategyUpdate",
    "Subscriber",
    "SubscriptionReconciler",
    "ToggleState",
    "ToggleUpdate",
    "Topic",
    "TopicBus",
    "TopicCodec",
    "TopicSnapshot",
    "TransactionView",
    "UndeclaredStateError",
    "UndoPlan",
    "UndoResult",
    "addresses",
    "apply_conditional_patches",
    "apply_updates",
    "batch",
    "block_writes",
    "computed",
    "export_state",
    "fresh_action_transaction",
    "history",
    "history_actions",
    "inspect_cells",
    "inspect_computed",
    "inspect_histories",
    "join_action",
    "on_action_commit",
    "on_action_outcome",
    "on_action_rollback",
    "relaxed_read",
    "resource",
    "restore_state",
    "state",
    "transaction",
    "untracked",
    "watch",
]
