"""Frontend-neutral component runtime and presentation state."""

from squid_layouts.runtime.component import Component
from squid_layouts.runtime.context import ContextKey
from squid_layouts.runtime.histories import (
    History,
    HistoryEntry,
    HistoryEntrySnapshot,
    HistoryError,
    HistorySnapshot,
    history,
    history_actions,
    inspect_histories,
)
from squid_layouts.runtime.presentation import (
    ActivePagers,
    CursorState,
    CursorUpdate,
    DisclosureState,
    PresentationSession,
    SelectionState,
    SessionUpdate,
    StrategyState,
    StrategyUpdate,
    ToggleState,
    ToggleUpdate,
    apply_updates,
)
from squid_layouts.runtime.reactivity import (
    ActionParticipant,
    CellReport,
    ComputedReport,
    Observation,
    ReactiveCycleError,
    ReactiveWriteError,
    SharedStateConflictError,
    StaleReactiveContextError,
    StateChange,
    StateDelta,
    UndeclaredStateError,
    addresses,
    batch,
    block_writes,
    computed,
    export_state,
    inspect_cells,
    inspect_computed,
    join_action,
    on_action_commit,
    restore_state,
    state,
    transaction,
    untracked,
)
from squid_layouts.runtime.resources import (
    AtomicResource,
    AtomicResourceStatus,
    Failed,
    Pending,
    PendingPolicy,
    Ready,
    Resource,
    ResourceNotReadyError,
    ResourceStatus,
    resource,
)
from squid_layouts.runtime.shared import Shared, SharedFactory, SharedPool
from squid_layouts.runtime.topics import (
    Address,
    BusSnapshot,
    CellAddress,
    KindKeyCodec,
    LocalTopicBus,
    Subscriber,
    SubscriptionReconciler,
    Topic,
    TopicBus,
    TopicCodec,
    TopicSnapshot,
    watch,
)


def __getattr__(name: str):
    if name == "ComponentRuntime":
        from squid_layouts.runtime.owner import ComponentRuntime

        return ComponentRuntime
    raise AttributeError(name)


__all__ = [
    "ActionParticipant",
    "ActivePagers",
    "Address",
    "AtomicResource",
    "AtomicResourceStatus",
    "BusSnapshot",
    "CellAddress",
    "CellReport",
    "Component",
    "ComponentRuntime",
    "ComputedReport",
    "ContextKey",
    "CursorState",
    "CursorUpdate",
    "DisclosureState",
    "Failed",
    "History",
    "HistoryEntry",
    "HistoryEntrySnapshot",
    "HistoryError",
    "HistorySnapshot",
    "KindKeyCodec",
    "LocalTopicBus",
    "Observation",
    "Pending",
    "PendingPolicy",
    "PresentationSession",
    "ReactiveCycleError",
    "ReactiveWriteError",
    "Ready",
    "Resource",
    "ResourceNotReadyError",
    "ResourceStatus",
    "SelectionState",
    "SessionUpdate",
    "Shared",
    "SharedFactory",
    "SharedPool",
    "SharedStateConflictError",
    "StaleReactiveContextError",
    "StateChange",
    "StateDelta",
    "StrategyState",
    "StrategyUpdate",
    "Subscriber",
    "SubscriptionReconciler",
    "ToggleState",
    "ToggleUpdate",
    "Topic",
    "TopicBus",
    "TopicCodec",
    "TopicSnapshot",
    "UndeclaredStateError",
    "addresses",
    "apply_updates",
    "batch",
    "block_writes",
    "computed",
    "export_state",
    "history",
    "history_actions",
    "inspect_cells",
    "inspect_computed",
    "inspect_histories",
    "join_action",
    "on_action_commit",
    "resource",
    "restore_state",
    "state",
    "transaction",
    "untracked",
    "watch",
]
