from typing import Any, Sequence, Mapping

class BuildRepository:
    """Repository for Build persistence and queries."""

    async def get_by_id(self, build_id: int) -> Any: ...
    async def get_by_message_id(self, message_id: int) -> Any: ...
    async def get_by_ids(self, build_ids: list[int]) -> list[Any]: ...
    async def get_by_filter(self, filter: Mapping[str, Any] | None = None) -> list[Any]: ...
    async def save(self, build: Any) -> None: ...
    async def delete(self, build_id: int) -> None: ...
    async def get_unsent_builds(self, server_id: int) -> list[Any] | None: ...

class BuildService:
    """Service for Build domain logic and orchestration."""

    async def create_build(self, data: dict[str, Any]) -> Any: ...
    async def update_build(self, build_id: int, data: dict[str, Any]) -> Any: ...
    async def confirm_build(self, build_id: int) -> None: ...
    async def deny_build(self, build_id: int) -> None: ...
    async def generate_embedding(self, build_id: int) -> list[float] | None: ...
    async def set_restrictions(self, build_id: int, restrictions: Sequence[str] | Mapping[str, Sequence[str]]) -> None: ...
    async def get_title(self, build_id: int) -> str: ...
    async def ai_generate_from_message(self, message: Any, *, prompt_path: str = "prompt.txt", model: str = "gpt-4.1-nano") -> Any: ... 