from typing import Any


class MessageRepository:
    """Repository for Message persistence and queries."""

    async def track_message(
        self, message: Any, purpose: str, *, build_id: int | None = None, vote_session_id: int | None = None
    ) -> None: ...
    async def update_message_edited_time(self, message: int | Any) -> None: ...
    async def untrack_message(self, message: int | Any) -> Any: ...
    async def get_outdated_messages(self, server_id: int) -> list[Any] | None: ...


class MessageService:
    """Service for Message domain logic and orchestration."""

    async def create_message(
        self, message: Any, purpose: str, *, build_id: int | None = None, vote_session_id: int | None = None
    ) -> None: ...
    async def edit_message_time(self, message: int | Any) -> None: ...
    async def remove_message(self, message: int | Any) -> Any: ...
    async def find_outdated_messages(self, server_id: int) -> list[Any] | None: ...
