from typing import Any, Literal

class VersionRepository:
    """Repository for Version persistence and queries."""

    async def fetch_all(self) -> list[Any]: ...
    async def get_versions_list(self, edition: Literal["Java", "Bedrock"]) -> list[Any]: ...
    async def get_newest_version(self, edition: Literal["Java", "Bedrock"]) -> str: ...
    async def find_versions_from_spec(self, version_spec: str) -> list[str]: ...

class VersionService:
    """Service for Version domain logic and orchestration."""

    async def list_versions(self, edition: Literal["Java", "Bedrock"]) -> list[Any]: ...
    async def get_latest_version(self, edition: Literal["Java", "Bedrock"]) -> str: ...
    async def resolve_versions(self, version_spec: str) -> list[str]: ... 