"""Exact target-shaped primitives for layouts that require presentation control.

Most applications should use the semantic nodes exported by :mod:`squid_layouts`. These
primitives are the escape hatch for target-specific structure and are intentionally grouped
behind ``squid_layouts.primitives``.
"""

from squid_layouts.emoji import Emoji, EmojiLike, normalize_emoji
from squid_layouts.primitives.constraints import (
    Alt,
    Alts,
    Condense,
    Drop,
    Never,
    Overflow,
    Paginate,
    Spill,
    Truncate,
    alts,
)
from squid_layouts.primitives.nodes import (
    ActionGroup,
    Boundary,
    Break,
    Budget,
    Button,
    Card,
    CardAuthor,
    CardField,
    CardFooter,
    CardMedia,
    CardText,
    Code,
    Content,
    EntitySelect,
    Extension,
    Fidelity,
    File,
    Footer,
    Gallery,
    GalleryItem,
    Heading,
    Lines,
    LinkButton,
    MediaCollection,
    Node,
    Option,
    Panel,
    PremiumButton,
    RawItem,
    RoutedButton,
    RoutedSelect,
    Row,
    Section,
    SelectMenu,
    Sep,
    Text,
    Thumbnail,
    Time,
    Variant,
    Variants,
    ZonedTime,
    as_nodes,
    card_text,
)
from squid_layouts.primitives.styles import ActionStyle, Color

__all__ = [
    "ActionGroup",
    "ActionStyle",
    "Alt",
    "Alts",
    "Boundary",
    "Break",
    "Budget",
    "Button",
    "Card",
    "CardAuthor",
    "CardField",
    "CardFooter",
    "CardMedia",
    "CardText",
    "Code",
    "Color",
    "Condense",
    "Content",
    "Drop",
    "Emoji",
    "EmojiLike",
    "EntitySelect",
    "Extension",
    "Fidelity",
    "File",
    "Footer",
    "Gallery",
    "GalleryItem",
    "Heading",
    "Lines",
    "LinkButton",
    "MediaCollection",
    "Never",
    "Node",
    "Option",
    "Overflow",
    "Paginate",
    "Panel",
    "PremiumButton",
    "RawItem",
    "RoutedButton",
    "RoutedSelect",
    "Row",
    "Section",
    "SelectMenu",
    "Sep",
    "Spill",
    "Text",
    "Thumbnail",
    "Time",
    "Truncate",
    "Variant",
    "Variants",
    "ZonedTime",
    "alts",
    "as_nodes",
    "card_text",
    "normalize_emoji",
]
