"""Stop minting foreign keys from sequences

`votes.vote_session_id`, `build_vote_sessions.vote_session_id` and
`delete_log_vote_sessions.vote_session_id` were each declared `GENERATED BY DEFAULT AS IDENTITY`
on top of being a foreign key into `vote_sessions.id`. The column means "the session this row
belongs to", so its value can only ever come from the parent; a sequence has no idea which
session that is.

`BY DEFAULT` rather than `ALWAYS` is why this has never been visible. The ORM always supplies
the column -- it is part of every one of these tables' primary key and none of them mark it
`init=False` -- so the sequence is never consulted and never advances. The failure is reserved
for any insert that omits the column: a backfill, a `COPY`, a hand-written statement during an
incident. That insert does not fail. It silently takes the next sequence number and attaches
the vote, or the build linkage, to whichever session happens to own that id.

`vote_session_options` and `generic_vote_sessions` are the same shape without the identity,
which is what says this was a slip in the reflected baseline rather than a convention.

Dropping the identity also drops the three backing sequences. Nothing reads them: every one is
still at its starting value, because no insert has ever gone through the default.

Revision ID: d5f9a2c7b481
Revises: c4e8f2a1b6d3
Create Date: 2026-08-17 12:00:00.000000+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "d5f9a2c7b481"
down_revision: str | Sequence[str] | None = "c4e8f2a1b6d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FOREIGN_KEYS_WITH_IDENTITY = (
    ("votes", "vote_session_id"),
    ("build_vote_sessions", "vote_session_id"),
    ("delete_log_vote_sessions", "vote_session_id"),
)


def upgrade() -> None:
    """Apply this revision."""
    for table, column in _FOREIGN_KEYS_WITH_IDENTITY:
        op.execute(f"ALTER TABLE public.{table} ALTER COLUMN {column} DROP IDENTITY IF EXISTS")


def downgrade() -> None:
    """Revert this revision."""
    # Restored without resetting the sequence position. That is faithful to what this
    # revision removed: these sequences were created at 1 and never advanced, because the
    # default they back has never been used.
    for table, column in _FOREIGN_KEYS_WITH_IDENTITY:
        op.execute(f"ALTER TABLE public.{table} ALTER COLUMN {column} ADD GENERATED BY DEFAULT AS IDENTITY")
