"""Carry the table and column comments the model docstrings now state.

Revision ID: a1b7f3c95d24
Revises: f8a4c7d2b5e9
Create Date: 2026-09-09 09:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "a1b7f3c95d24"
down_revision: str | None = "f8a4c7d2b5e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Comments are generated from model docstrings by `Base.__init_subclass__`, so a reworded
# docstring drifts the schema until a migration carries it across. Each entry is
# (table, column, new, old) or (table, new, old); `old` is what the previous pass left,
# so `downgrade` restores it exactly rather than dropping the comment.

_COLUMN_COMMENTS: tuple[tuple[str, str, str | None, str | None], ...] = (
    (
        "account_merge_tickets",
        "code_digest",
        "Digest, never the code: the plaintext is shown once at mint time and never stored.",
        "Digest, never the code. The plaintext is shown once at mint time and never stored, exactly\nas a verification code is.",
    ),
    (
        "account_merge_tickets",
        "expires_at",
        "The TTL equals `MERGE_PROOF_MAX_AGE_SECONDS`, so a ticket stays redeemable for exactly as long\nas `RecentAccountProof` accepts the `created_at` it stands for.",
        "Doubles as the proof timestamp: a ticket is redeemable for exactly as long as\n`RecentAccountProof` accepts the authentication that minted it.",
    ),
    (
        "account_profiles",
        "avatar_identity_id",
        "The linked identity this profile's avatar is rendered from.\n\n`SET NULL` so unlinking that identity clears the avatar. That the identity belongs to this same\naccount is checked in the repository: the composite foreign key enforcing it cannot coexist with\n`ON DELETE SET NULL`.",
        "The linked identity this profile's avatar is rendered from.\n\n`SET NULL` so unlinking that identity clears the avatar rather than leaving a render pointing\nat a subject we no longer hold. Ownership — that the identity belongs to this same account —\nis checked in the repository, since the composite foreign key that would enforce it here\ncannot coexist with `ON DELETE SET NULL`.",
    ),
    (
        "api_keys",
        "created_by_account_id",
        "Account that created the credential; set null if that account is deleted.",
        "Account that created the credential, when known.",
    ),
    (
        "api_keys",
        "expires_at",
        "Instant after which authentication is rejected; null means the credential never expires.",
        "Optional instant after which authentication is rejected.",
    ),
    (
        "api_keys",
        "key_id",
        "Public lookup portion of the API token; unique, and the only part an index is built on.",
        "Public lookup portion of the API token.",
    ),
    (
        "api_keys",
        "last_used_at",
        "Most recent use, rewritten at most once a minute, so it lags a busy key by up to that.",
        "Most recent throttled usage timestamp.",
    ),
    (
        "api_keys",
        "owner_account_id",
        "Account responsible for the credential, whose permissions bounded its scopes at issue.\n\nNull for a key issued by the CLI bootstrap path, which has no owner to bound it, and set null\nagain if that account is deleted.",
        "Optional account responsible for the credential.",
    ),
    (
        "api_keys",
        "revoked_at",
        "When the credential was revoked; null while it is still usable.",
        "When the credential was revoked, or ``None`` while active.",
    ),
    (
        "api_keys",
        "scopes",
        "Permission patterns bounding what this credential may do, stored sorted and de-duplicated.\n\nText rather than an enum because the catalogue is open: a pattern granted today can select a\nnode registered tomorrow.",
        "Capabilities granted to this credential.",
    ),
    (
        "api_keys",
        "secret_hash",
        "HMAC-SHA256 digest of the unrecoverable token secret.\n\nKeyed by a deployment pepper that never reaches this database, so these rows alone cannot\nauthenticate anything. See `docs/credential-hashing.md`.",
        "HMAC-SHA256 digest of the unrecoverable token secret.\n\nKeyed by a deployment pepper that never reaches this database; see\n`docs/credential-hashing.md`.",
    ),
    (
        "build_schematics",
        "analyzed_at",
        "When this analysis was written. Re-analysis under a newer engine moves it forward.",
        None,
    ),
    (
        "build_schematics",
        "declared_author",
        "The author written inside the file. Uploader-controlled, and not an account reference.",
        None,
    ),
    (
        "build_schematics",
        "declared_name",
        "The name written inside the file by its author. Uploader-controlled; display only.",
        None,
    ),
    (
        "build_schematics",
        "entity_count",
        "Entities stored in the file, such as item frames and minecarts. Never counted as blocks.",
        None,
    ),
    (
        "build_schematics",
        "license_code",
        "Creative Commons license the uploader granted. Required once visibility is `public_download`.",
        None,
    ),
    (
        "build_schematics",
        "published_at",
        "When public downloads began. NULL blocks them however complete the rest of the row is.",
        None,
    ),
    (
        "build_schematics",
        "region_names",
        "Names of the regions the file declares. Litematic files can carry several; other formats one.",
        None,
    ),
    (
        "build_schematics",
        "rights_attested_at",
        "When someone affirmed the right to redistribute this file under `license_code`.",
        None,
    ),
    (
        "build_schematics",
        "rights_attested_by_account_id",
        "Who made that attestation. `RESTRICT`, because the claim must stay attributable.",
        None,
    ),
    (
        "build_schematics",
        "sanitization_report",
        "The sanitizer's audit output: what it stripped from the file and what it left alone.",
        None,
    ),
    (
        "build_schematics",
        "sanitized_at",
        "When the sanitizer last ran. Set with `sanitizer_version` and `sanitization_report`, or all NULL.",
        None,
    ),
    (
        "build_schematics",
        "sanitizer_version",
        "Which sanitizer build produced the report, so a fixed sanitizer means a visible re-run.",
        None,
    ),
    (
        "build_schematics",
        "withdrawn_at",
        "When downloads were withdrawn. Set, it blocks them permanently without deleting the row.",
        None,
    ),
    ("build_tag_assignments", "boolean_value", "Non-null exactly for boolean tags.", None),
    (
        "build_tag_assignments",
        "display_order",
        "Overrides the definition's default order on this build; null keeps it.",
        None,
    ),
    (
        "build_tag_assignments",
        "display_unit_key",
        "Unit the value is shown in; null falls back to the definition's default display unit.",
        None,
    ),
    ("build_tag_assignments", "evidence", "Free text backing the claim, such as a link to a test.", None),
    (
        "build_tag_assignments",
        "numeric_value",
        "In the definition's canonical unit. Non-null exactly for numeric tags, and always finite.",
        None,
    ),
    (
        "build_tag_assignments",
        "provenance",
        "Where the assignment came from: submitted, inferred, moderated or legacy_import.",
        None,
    ),
    ("build_tag_assignments", "text_value", "Non-null exactly for text tags.", None),
    (
        "build_tag_assignments",
        "value_type",
        "Copied from the definition and enforced against it by a foreign key; picks which value column is filled.",
        None,
    ),
    (
        "build_vote_sessions",
        "changes",
        "Pending edits as `[field, old, new]` triples, applied to the build when the vote passes.",
        None,
    ),
    (
        "cli_device_enrollments",
        "approved_at",
        "When the browser approved; null exactly while approved_by_account_id is.",
        None,
    ),
    (
        "cli_device_enrollments",
        "approved_by_account_id",
        "Account that approved in the browser; null exactly while approved_at is.",
        None,
    ),
    (
        "cli_device_enrollments",
        "client_instance_id",
        "The CLI installation that started this; how many it may have live at once is bounded.",
        None,
    ),
    (
        "cli_device_enrollments",
        "device_code_hash",
        "Keyed digest of the code the CLI polls with; the code itself is disclosed once and never stored.",
        None,
    ),
    (
        "cli_device_enrollments",
        "exchanged_at",
        "When the enrollment was spent for a device and session; it may only be spent once.",
        None,
    ),
    ("cli_device_enrollments", "expires_at", "When the enrollment stops being approvable or exchangeable.", None),
    ("cli_device_enrollments", "label", "Device name shown on the browser approval screen.", None),
    (
        "cli_device_enrollments",
        "public_key",
        "Raw Ed25519 public key whose private half the exchange must prove possession of.",
        None,
    ),
    ("cli_device_enrollments", "revoked_at", "When the enrollment was revoked; null while it is still usable.", None),
    (
        "cli_device_enrollments",
        "user_code_hash",
        "Keyed digest of the normalized code a person types into the browser.",
        None,
    ),
    ("cli_devices", "account_id", "Owner; deleting the account deletes the device and everything beneath it.", None),
    ("cli_devices", "client_instance_id", "Most recent CLI installation to present this key.", None),
    ("cli_devices", "label", "Device name its owner sees when listing or revoking devices.", None),
    ("cli_devices", "last_used_at", "Last enrollment exchange or challenge this device completed.", None),
    (
        "cli_devices",
        "public_key",
        "Raw Ed25519 public key, unique across all devices, and the identity that signs every proof.",
        None,
    ),
    ("cli_devices", "revoked_at", "When the owner revoked the device; revoking also revokes its live sessions.", None),
    (
        "cli_session_challenges",
        "consumed_at",
        "When the nonce was spent for a session; null while the challenge is still outstanding.",
        None,
    ),
    (
        "cli_session_challenges",
        "expires_at",
        "When the challenge stops being consumable; shorter-lived than an enrollment.",
        None,
    ),
    (
        "cli_session_challenges",
        "nonce_hash",
        "Keyed digest of the nonce; the nonce is disclosed to the device once and never stored.",
        None,
    ),
    (
        "cli_sessions",
        "expires_at",
        "When the token stops authenticating; the CLI signs a new challenge to get another.",
        None,
    ),
    (
        "cli_sessions",
        "revoked_at",
        "When this session was revoked, directly or with its device; null while it is usable.",
        None,
    ),
    (
        "cli_sessions",
        "token_hash",
        "Keyed digest of the bearer token, which is disclosed to the CLI once and never stored.",
        None,
    ),
    ("discord_sync_queue", "action", "'refresh' re-renders the resource's posts, 'delete' removes them.", None),
    ("discord_sync_queue", "attempts", "Failed drains of this row; reaching the drainer's ceiling sets dead_at.", None),
    (
        "discord_sync_queue",
        "available_at",
        "When this row next becomes claimable, and the only column backoff writes.\n\nSeparate from enqueued_at so a repeatedly failing row keeps its place in FIFO order and still reports its true\nage to the queue-health gauges.",
        "When this row next becomes claimable, and the only column backoff writes.\n\nKept separate from `enqueued_at` so a repeatedly failing row keeps its place in\nFIFO order and still reports its true age to the queue-health gauges.",
    ),
    (
        "discord_sync_queue",
        "claim_token",
        "Database-minted fence the claiming worker's acknowledgement must match.\n\nNullable so a worker from an older release, which stamps only claimed_at, can still drain the queue.",
        "The database-minted fencing token handed to the worker that claimed this row.\n\nNullable for now so code from the previous release, which stamps only\n`claimed_at`, can keep draining the queue across a deploy window.",
    ),
    (
        "discord_sync_queue",
        "claimed_at",
        "When the current worker claimed the row; a claim older than the visibility timeout may be taken over.",
        None,
    ),
    (
        "discord_sync_queue",
        "dead_at",
        "Set when the row is abandoned after too many attempts; a dead row is never claimed again.",
        None,
    ),
    (
        "discord_sync_queue",
        "generation",
        "A globally monotonic staleness token from a sequence, compared against a post's applied revision.\n\nNot a per-row counter: acknowledging deletes the row, so a counter would restart at 1 and could name a\nrevision a post had already applied.",
        "A globally monotonic staleness token, not a per-row counter.\n\nAcknowledging a job deletes its queue row, so a counter restarted at 1 on the next\nenqueue and could name a revision below one a post had already applied. Sequence\nvalues survive that because they are never rolled back or reused.",
    ),
    ("discord_sync_queue", "last_error", "Truncated text of the most recent failure.", None),
    (
        "discord_sync_queue",
        "resource_kind",
        "What source_key identifies: build, vote_session or starboard_entry.",
        None,
    ),
    (
        "discord_sync_queue",
        "source_key",
        "The resource's id as text; a starboard entry is '<starboard_id>:<origin_message_id>'.",
        None,
    ),
    ("domain_event_deliveries", "attempts", "Failed handler runs; reaching the consumer's ceiling sets dead_at.", None),
    (
        "domain_event_deliveries",
        "available_at",
        "Earliest time this delivery may be claimed; a failure pushes it out by the queue's backoff.",
        None,
    ),
    (
        "domain_event_deliveries",
        "claim_count",
        "How often the row has been claimed, including takeovers, which attempts does not count.",
        None,
    ),
    (
        "domain_event_deliveries",
        "claim_token",
        "Fences the acknowledgement: a worker whose claim was taken over cannot complete or fail the row.",
        None,
    ),
    (
        "domain_event_deliveries",
        "claimed_at",
        "When the current worker claimed it; a claim older than the visibility timeout may be taken over.",
        None,
    ),
    (
        "domain_event_deliveries",
        "dead_at",
        "Set when the delivery is abandoned; a dead row is never claimed again.",
        None,
    ),
    ("domain_event_deliveries", "last_error", "Truncated text of the most recent failure.", None),
    ("domain_events", "aggregate_kind", "What aggregate_id identifies, such as build or vote_session.", None),
    ("domain_events", "event_type", "Dotted name, such as build.confirmed, that consumers dispatch on.", None),
    ("domain_events", "payload", "The transition's own data, read according to schema_version.", None),
    (
        "domain_events",
        "schema_version",
        "Version of the payload shape; a consumer that does not accept it dead-letters its delivery.",
        None,
    ),
    (
        "error_reports",
        "reference",
        "The shortened form shown to the user, indexed because it is what they quote back.\n\nA 48-bit prefix of the correlation ID, so it is not unique: a unique constraint would turn a collision into a\nfailure to record the second error rather than an ambiguous lookup.",
        "The shortened form shown to the user, indexed because it is what they quote back.\n\nNot unique: it is a 48-bit prefix of the correlation ID, so a collision is possible even\nthough it is vanishingly unlikely, and a unique constraint would turn that into a failure to\nrecord the second error rather than an ambiguous lookup.",
    ),
    (
        "generic_vote_sessions",
        "deadline",
        "When the poll closes; the scheduler closes it on the first pass after this instant.",
        None,
    ),
    (
        "generic_vote_sessions",
        "guild_id",
        "The guild that owns the poll and weighs its ballots.\n\nNullable so a transport with no guild -- the REST API, a standalone draft -- can create a poll\nand attach its presentation messages afterwards. Required when scope is network.",
        "The guild whose emoji palette the poll was drafted against.\n\nNullable so a poll can be created by a transport that has no guild -- the REST API\nor a standalone draft -- and have its presentation messages attached afterwards.",
    ),
    (
        "generic_vote_sessions",
        "visibility",
        "How much is disclosed while open: anonymous_live, visible_live, or anonymous_hidden.",
        None,
    ),
    ("guild_vote_role_weights", "multiplier", "Finite positive weight a member of this role votes at.", None),
    ("guild_vote_role_weights", "role_id", "The Discord role, which only means anything inside `guild_id`.", None),
    (
        "idempotency_requests",
        "completed_at",
        "When the response was stored; null while the request is still in progress.",
        None,
    ),
    (
        "idempotency_requests",
        "expires_at",
        "When the reservation stops replaying and becomes eligible for deletion.",
        None,
    ),
    ("idempotency_requests", "idempotency_key", "The key the caller sent, unique within its principal.", None),
    (
        "idempotency_requests",
        "method",
        "HTTP method of the reserved request, kept for diagnostics and response authentication.",
        None,
    ),
    (
        "idempotency_requests",
        "principal",
        "The caller namespace a key is reserved in; keys of different callers never collide.\n\nThe application layer calls this the *caller*, as do the `RateLimit-Policy` partition and\n`SQUID_API_RATE_LIMIT_PRINCIPAL_REQUESTS`.",
        "The caller namespace a key is reserved in.\n\nThe application layer calls this the *caller*; the column keeps the older\nword because renaming it needs a migration, a rewrite of the unique index it\nanchors, and a redeploy window, for a name no client ever sees. The same\ntrade applies to the `principal` partition in `RateLimit-Policy` and to\n`SQUID_API_RATE_LIMIT_PRINCIPAL_REQUESTS`, both of which deployments and\nclients can observe. If the ban is meant repo-wide, that is its own commit.",
    ),
    (
        "idempotency_requests",
        "request_fingerprint",
        "Digest of the request this key was reserved for; a replay that differs is a conflict.",
        None,
    ),
    (
        "idempotency_requests",
        "response_body_ciphertext",
        "AES-256-GCM body, bound to this row's identity so it cannot be replayed under another key.",
        None,
    ),
    (
        "idempotency_requests",
        "response_body_key_id",
        "Which keyring entry sealed the body; a rotated-out key makes the row unreadable.",
        None,
    ),
    ("idempotency_requests", "response_body_nonce", "The 12-byte AES-GCM nonce, generated per response.", None),
    (
        "idempotency_requests",
        "response_headers",
        "Headers replayed with the retained response, and authenticated as part of its ciphertext.",
        None,
    ),
    (
        "idempotency_requests",
        "response_status",
        "Status of the retained response; null until the request completes.",
        None,
    ),
    (
        "idempotency_requests",
        "route",
        "Route template of the reserved request, kept for diagnostics and response authentication.",
        None,
    ),
    (
        "idempotency_requests",
        "state",
        "Either ``in_progress`` or ``completed``; a check constraint ties the response columns to it.",
        None,
    ),
    (
        "media_artifact_objects",
        "attempts",
        "Failed deletion attempts, reset to zero when the key is re-registered after a deletion.",
        None,
    ),
    (
        "media_artifact_objects",
        "available_at",
        "When cleanup may next try this key, and the only column deletion backoff writes.",
        None,
    ),
    (
        "media_artifact_objects",
        "cleanup_claim_token",
        "Fence a cleaner's acknowledgement must still match, so a stale cleaner cannot report a delete.",
        None,
    ),
    (
        "media_artifact_objects",
        "cleanup_claimed_at",
        "When the live cleanup claim was taken; set together with `cleanup_claim_token` or not at all.",
        None,
    ),
    (
        "media_artifact_objects",
        "deleted_at",
        "When the object's deletion was confirmed; `NULL` means the bytes are still in storage.",
        None,
    ),
    ("media_artifact_objects", "first_upload_id", "The upload that first registered this key.", None),
    (
        "media_artifact_objects",
        "last_seen_at",
        "Last registration of this key. A move during a delete makes cleanup retry immediately.",
        None,
    ),
    (
        "media_artifact_objects",
        "last_upload_id",
        "The upload that registered this key most recently; identical bytes reuse one object.",
        None,
    ),
    (
        "media_artifact_objects",
        "sha256",
        "Lowercase hex SHA-256 of the object. Registering the key again with a different digest fails.",
        None,
    ),
    (
        "media_artifact_publications",
        "claim_token",
        "The job claim that holds this lease; a reclaimed job's old token no longer protects the key.",
        None,
    ),
    (
        "media_artifact_publications",
        "expires_at",
        "When the lease stops protecting the key, so a lost worker's keys become collectable.",
        None,
    ),
    (
        "media_artifacts",
        "byte_size",
        "Artifact size in bytes; the sum over a draft's outputs is limit-checked at completion.",
        None,
    ),
    (
        "media_artifacts",
        "object_key",
        "Key of the artifact in storage, derived from `sha256` so identical bytes share one object.",
        None,
    ),
    (
        "media_artifacts",
        "role",
        "`output`, `poster`, or `report` — the normalized file, its still image, or the JSON report.",
        None,
    ),
    ("media_artifacts", "sha256", "Lowercase hex SHA-256 of the artifact bytes.", None),
    ("media_artifacts", "width", "Pixel width, `NULL` for the `report` role and required for the others.", None),
    (
        "media_normalization_jobs",
        "attempts",
        "Failed attempts so far. The job dies once this reaches the runner's `max_attempts`.",
        None,
    ),
    (
        "media_normalization_jobs",
        "available_at",
        "When the job next becomes claimable, and the only column retry backoff writes.",
        None,
    ),
    (
        "media_normalization_jobs",
        "claim_token",
        "Fence the claiming worker's acknowledgements must still match; reclaiming mints a new one.",
        None,
    ),
    (
        "media_normalization_jobs",
        "claimed_at",
        "When the live claim was taken; a claim older than the visibility timeout is reclaimable.",
        None,
    ),
    (
        "media_normalization_jobs",
        "discarded_at",
        "When the upload was withdrawn from its draft, which invalidates any live claim.",
        None,
    ),
    ("media_normalization_jobs", "last_error", "The most recent failure, truncated to 4000 characters.", None),
    (
        "media_normalization_jobs",
        "status",
        "`pending`, `claimed`, `completed`, `dead`, or `discarded`; the last three are terminal.",
        None,
    ),
    ("media_uploads", "draft_id", "The submission draft this upload belongs to; limits are counted per draft.", None),
    ("media_uploads", "id", "Caller-minted upload id, also the identity of the normalization job.", None),
    (
        "media_uploads",
        "kind",
        "`image` or `video`. Only a video may set `strip_audio` or produce a poster artifact.",
        None,
    ),
    (
        "media_uploads",
        "raw_deleted_at",
        "When the raw object's deletion was confirmed; `NULL` while it is still in storage.",
        None,
    ),
    ("media_uploads", "source_byte_size", "Size of the raw object in bytes.", None),
    (
        "media_uploads",
        "source_content_type",
        "Content type claimed at upload. Never trusted for typing; the worker probes the bytes.",
        None,
    ),
    (
        "media_uploads",
        "source_object_key",
        "Key of the raw object in storage. Unique, so two uploads never share staged bytes.",
        None,
    ),
    (
        "media_uploads",
        "source_sha256",
        "Lowercase hex SHA-256 of the raw bytes, re-verified before normalization.",
        None,
    ),
    ("media_uploads", "strip_audio", "Whether the normalized video drops its audio streams.", None),
    (
        "minecraft_paper_installations",
        "credential_version",
        "Bumped by every rotation; challenges and grants naming an older version stop authenticating.",
        None,
    ),
    ("minecraft_paper_installations", "label", "Server name its owner sees when listing installations.", None),
    (
        "minecraft_paper_installations",
        "owner_account_id",
        "Owner; deleting the account deletes the installation and everything derived from it.",
        None,
    ),
    ("minecraft_paper_installations", "public_address", "Published connection address.", None),
    ("minecraft_paper_installations", "public_description", "Published free-text description.", None),
    ("minecraft_paper_installations", "public_display_name", "Published server name.", None),
    (
        "minecraft_paper_installations",
        "public_profile_enabled",
        "Whether the owner published this server; the public columns below are shown only when true.",
        None,
    ),
    ("minecraft_paper_installations", "public_website_url", "Published website link.", None),
    (
        "minecraft_paper_installations",
        "revoked_at",
        "When the owner revoked the installation; null while it may authenticate.",
        None,
    ),
    (
        "minecraft_paper_installations",
        "rotated_at",
        "Most recent secret rotation; null while the original credential is still in use.",
        None,
    ),
    (
        "minecraft_paper_installations",
        "secret_hash",
        "Keyed digest of the installation credential, which is disclosed once and never stored.",
        None,
    ),
    (
        "minecraft_paper_installations",
        "sponsor_opt_in",
        "Whether the owner opted into sponsorship, which requires a published profile.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "approved_at",
        "When the browser approved; null exactly while approved_by_account_id is.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "approved_by_account_id",
        "Account that approved in the browser; null exactly while approved_at is.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "device_code_hash",
        "Keyed digest of the code the client polls with; the code is disclosed once and never stored.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "exchanged_at",
        "When the challenge was spent for a grant; it may only be spent once.",
        None,
    ),
    ("minecraft_player_challenges", "expires_at", "When the challenge stops being approvable or exchangeable.", None),
    (
        "minecraft_player_challenges",
        "installation_credential_version",
        "Credential generation of that server; a rotation makes this challenge unexchangeable.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "installation_id",
        "Paper server that started this; set exactly when origin is ``paper``.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "java_uuid",
        "The Java account being authorized; only an account holding it verified may approve.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "origin",
        "Either ``paper`` or ``fabric``; it decides which of the columns below must be set.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "pkce_s256_challenge",
        "RFC 7636 S256 challenge the exchange must prove; set exactly when origin is ``fabric``.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "revoked_at",
        "When the challenge was revoked, which rotating or revoking its installation also does.",
        None,
    ),
    (
        "minecraft_player_challenges",
        "user_code_hash",
        "Keyed digest of the normalized code a player types into the browser.",
        None,
    ),
    (
        "minecraft_player_grants",
        "account_id",
        "Account the token authenticates as, taken from whoever approved the challenge.",
        None,
    ),
    (
        "minecraft_player_grants",
        "challenge_id",
        "The challenge this grant was exchanged from; one grant per challenge.",
        None,
    ),
    (
        "minecraft_player_grants",
        "expires_at",
        "When the token stops authenticating; shorter-lived than the challenge that produced it.",
        None,
    ),
    (
        "minecraft_player_grants",
        "installation_credential_version",
        "Credential generation the grant is fenced to; a rotation stops it authenticating.",
        None,
    ),
    (
        "minecraft_player_grants",
        "installation_id",
        "Paper server this token is bound to; set exactly when origin is ``paper``.",
        None,
    ),
    (
        "minecraft_player_grants",
        "java_uuid",
        "The Java account the token speaks for; authentication rechecks the account still holds it.",
        None,
    ),
    (
        "minecraft_player_grants",
        "origin",
        "Either ``paper`` or ``fabric``; a token is refused on the other transport.",
        None,
    ),
    (
        "minecraft_player_grants",
        "revoked_at",
        "When the grant was revoked, directly or with its installation; null while it is usable.",
        None,
    ),
    (
        "minecraft_player_grants",
        "token_hash",
        "Keyed digest of the player token, which is disclosed once and never stored.",
        None,
    ),
    ("oauth_states", "code_verifier", "PKCE verifier whose S256 hash went to the provider as the challenge.", None),
    (
        "oauth_states",
        "expires_at",
        "Ten minutes after minting; a state consumed later is refused rather than redeemed.",
        None,
    ),
    (
        "oauth_states",
        "redirect_to",
        "Where to send the browser after login; null returns it to the default landing page.",
        None,
    ),
    ("oauth_states", "state", "The opaque value handed to the provider and returned on the callback.", None),
    (
        "permission_roles",
        "rank",
        "Management hierarchy only: who may edit whom. Never consulted during permission\nresolution (property P10), so reordering roles cannot change an authorization outcome.",
        "Management hierarchy only: who may edit whom. Deliberately absent from\npermission resolution, so reordering roles can never change an authorization\noutcome. Enforced by property P10.",
    ),
    (
        "record_computation_runs",
        "is_active",
        "Whether this run is the published one; at most one run per build kind and version is.",
        None,
    ),
    (
        "record_computation_runs",
        "status",
        "'running' while the run is being written, then 'completed' or 'failed'.",
        None,
    ),
    (
        "record_definitions",
        "category_key",
        "Serialized identity of the competing category: build kind, base shape, and its restrictions.",
        None,
    ),
    (
        "record_definitions",
        "materialization_source",
        "Why the definition exists.\n\n'eager' for a generated category, 'seeded' for a fixture, and 'public_lookup' for an exact\ncategory a user asked for, which later rebuilds keep materializing.",
        None,
    ),
    (
        "record_definitions",
        "title_diagnostics",
        "Formatter complaints about unknown or contradictory taxonomy in the title; empty when clean.",
        None,
    ),
    (
        "record_holder_history",
        "held_until",
        "When the next holder took the record; NULL while this interval is still open.",
        None,
    ),
    (
        "record_holder_history",
        "metric_snapshot",
        "The measurements that won this interval, in the same shape as a holder's snapshot.",
        None,
    ),
    (
        "record_holder_history",
        "predecessor_id",
        "The interval this one superseded, chaining a definition's chronology; NULL for the first.",
        None,
    ),
    (
        "record_recompute_queue",
        "attempts",
        "Failed rebuilds so far; this queue never dead-letters, it only backs off further.",
        None,
    ),
    (
        "record_recompute_queue",
        "claim_token",
        "The database-minted fencing token handed to the worker that leased this scope.\n\nScopes are leased in batches and acknowledged as a set, so the token is what tells a finishing\nworker's acknowledgement from work enqueued during its run.",
        "The database-minted fencing token handed to the worker that leased this scope.\n\nScopes are leased in batches and acknowledged as a set, so the token is what\ntells a finishing worker's acknowledgement from work enqueued during its run.",
    ),
    (
        "record_recompute_queue",
        "locked_at",
        "When a worker leased this scope; cleared on release and by a fresh request for the scope.",
        None,
    ),
    (
        "record_recompute_queue",
        "scope_key",
        "Unique `kind:build_id` (or `kind:*`) scope; re-requesting a scope re-arms this row.",
        None,
    ),
    (
        "record_result_holders",
        "metric_snapshot",
        "The measurements this record compared, as computed.\n\nVolume, timing values in game ticks, or completion date, depending on the record class.",
        None,
    ),
    ("record_result_holders", "rank", "Display order among co-holders; tied holders share a rank.", None),
    (
        "record_result_holders",
        "title",
        "The rendered record title.\n\nA holder that is absent from the pinned current version gets a ` [BROKEN]` suffix.",
        None,
    ),
    (
        "record_results",
        "gap_reasons",
        'The facts whose absence blocked resolution, as `{"missing": [{"build_id", "field"}]}`.',
        None,
    ),
    (
        "record_results",
        "history_complete",
        "False when a candidate has no completion date, so the reconstructed chronology may skip periods.",
        None,
    ),
    (
        "record_results",
        "provisional_build_id",
        "One of the builds that would hold an unresolved record once its gaps are filled.",
        None,
    ),
    (
        "record_results",
        "status",
        "The outcome for this definition.\n\n'resolved' has holders, 'unresolved' means a tie needs facts nobody supplied, and\n'no_candidate' means no build supplies the fact this record compares.",
        None,
    ),
    (
        "record_rulesets",
        "activated_at",
        "When this ruleset became the active one; NULL on every superseded ruleset.",
        None,
    ),
    (
        "schematic_files",
        "created_at",
        "When these bytes were first stored. Re-uploading the same file does not move it.",
        None,
    ),
    ("schematic_files", "object_key", "Object-storage key holding the payload, derived from the digest.", None),
    (
        "schematic_jobs",
        "attempts",
        "Failed attempts so far; a typed schematic failure dies on the first one rather than retrying.",
        None,
    ),
    (
        "schematic_jobs",
        "available_at",
        "When this row next becomes claimable, and the only column backoff writes.",
        None,
    ),
    (
        "schematic_jobs",
        "claimed_at",
        "When a worker leased this row. NULL means unclaimed and, if due and unfinished, ready.",
        None,
    ),
    ("schematic_jobs", "completed_at", "When the operation succeeded. Mutually exclusive with `dead_at`.", None),
    ("schematic_jobs", "created_at", "When the job was submitted, unchanged by retries.", None),
    (
        "schematic_jobs",
        "dead_at",
        "When the job failed for good. The client raises the error described below from it.",
        None,
    ),
    (
        "schematic_jobs",
        "error_context",
        "The failed exception's structured context, used to reconstruct it client-side.",
        None,
    ),
    (
        "schematic_jobs",
        "error_kind",
        "Which typed exception the client rebuilds: `invalid`, `too_large`, `unavailable`, `timeout`,\n`crashed`, or `internal`.",
        None,
    ),
    (
        "schematic_jobs",
        "expires_at",
        "When cleanup may delete this row and its result artifact. Set on reaching a terminal state.",
        None,
    ),
    (
        "schematic_jobs",
        "input_keys",
        "Object-storage keys of the binary inputs, in the order the operation reads them.",
        None,
    ),
    ("schematic_jobs", "last_error", "The most recent failure's message.", None),
    (
        "schematic_jobs",
        "operation",
        "Which native-engine call to make, constrained to the seven the worker implements.",
        None,
    ),
    (
        "schematic_jobs",
        "params",
        "The call's non-binary arguments, already wire-encoded. Never contains schematic bytes.",
        None,
    ),
    ("schematic_jobs", "result", "The wire-encoded non-binary result, readable once `completed_at` is set.", None),
    (
        "schematic_jobs",
        "result_object_key",
        "Object-storage key of a binary result, if the operation produced one. Deleted with the row.",
        None,
    ),
    (
        "schematic_render_queue",
        "attempts",
        "Failed attempts so far; the row dies once this reaches the worker's configured maximum.",
        None,
    ),
    (
        "schematic_render_queue",
        "claimed_at",
        "When a worker leased this row. NULL means unclaimed and, if due, ready.",
        None,
    ),
    ("schematic_render_queue", "dead_at", "When retries were given up on. Set, this row is never claimed again.", None),
    (
        "schematic_render_queue",
        "enqueued_at",
        "When the render was last requested. Reset when a new primary schematic is attached.",
        None,
    ),
    ("schematic_render_queue", "last_error", "The most recent failure's message, truncated to 4000 characters.", None),
    (
        "schematic_renders",
        "byte_size",
        "PNG size in bytes, read before the object so an oversized preview is refused unfetched.",
        None,
    ),
    (
        "schematic_renders",
        "object_key",
        "Object-storage key of the PNG. NULL means only the URL is known and the bytes cannot be re-read.",
        None,
    ),
    (
        "schematic_renders",
        "url",
        "Where the preview is served from, and the URL projected onto the build as a render link.",
        None,
    ),
    ("schematic_renders", "width", "Rendered image width in pixels, from the recipe rather than the schematic.", None),
    (
        "search_document_facets",
        "field_name",
        "The public search field this value answers, or `tag:<id>` for a data-tag field.",
        None,
    ),
    (
        "search_document_facets",
        "ordinal",
        "Position among a document's values for the same field, so multi-valued fields stay distinct.",
        None,
    ),
    (
        "search_documents",
        "combined_vector",
        "Title and tags weighted A, subtitle B, description C, for ranked full-text search.",
        None,
    ),
    (
        "search_documents",
        "document_data",
        "Kind-specific payload rendered into search hits; never queried as a filter.",
        None,
    ),
    (
        "search_documents",
        "embedding",
        "NULL until the embedding queue fills it, and again whenever the source hash changes.",
        None,
    ),
    (
        "search_documents",
        "embedding_model",
        "The model that produced `embedding`; semantic queries only match vectors from their own model.",
        None,
    ),
    ("search_documents", "fuzzy_text", "Normalized title, subtitle and tags joined for trigram similarity.", None),
    (
        "search_documents",
        "normalized_title",
        "Case-folded, whitespace-collapsed, unaccented title used for exact matching and ordering.",
        None,
    ),
    (
        "search_documents",
        "resource_kind",
        "'build', 'record', or 'metadata' for anything else that is searchable.",
        None,
    ),
    (
        "search_documents",
        "source_hash",
        "Hash of the projected content; a change clears the embedding and re-enqueues embedding work.",
        None,
    ),
    (
        "search_documents",
        "source_key",
        "Identity of the projected resource within its kind, such as a build id or `tag:12`.",
        None,
    ),
    (
        "search_documents",
        "status",
        "The source's submission status, which gates build visibility; NULL for kinds without one.",
        None,
    ),
    (
        "search_embedding_queue",
        "dead_at",
        "When the job exhausted its attempts; a dead row is retained and never claimed again.",
        None,
    ),
    (
        "search_embedding_queue",
        "source_hash",
        "The document content this job embeds; the vector write is rejected if the hash moved on.",
        None,
    ),
    ("search_projection_queue", "action", "'upsert' to reproject the resource, 'delete' to drop its document.", None),
    (
        "search_projection_queue",
        "dead_at",
        "When the item exhausted its attempts; a dead row is retained and never claimed again.",
        None,
    ),
    (
        "search_projection_queue",
        "source_key",
        "With `resource_kind`, the resource to refresh; one pending row per resource.",
        None,
    ),
    ("server_settings", "builds_channel_id", "Where confirmed build cards are posted; null when unset.", None),
    (
        "server_settings",
        "fastest_channel_id",
        "Where fastest-record announcements go; null when unset, and no two guilds may share a channel.",
        None,
    ),
    (
        "server_settings",
        "first_channel_id",
        "Where first-record announcements go; null when unset, and no two guilds may share a channel.",
        None,
    ),
    (
        "server_settings",
        "in_server",
        "False once the bot leaves the guild; the settings are kept so a rejoin restores them.",
        None,
    ),
    (
        "server_settings",
        "smallest_channel_id",
        "Where smallest-record announcements go; null when unset, and no two guilds may share a channel.",
        None,
    ),
    ("server_settings", "voting_channel_id", "Where vote sessions are posted; null when unset.", None),
    ("starboard_emojis", "direction", "'up' adds the vote's weight to the score, 'down' subtracts it.", None),
    (
        "starboard_emojis",
        "multiplier",
        "Scales a vote cast with this emoji, on top of the voter's role multiplier.",
        None,
    ),
    ("starboard_emojis", "position", "Display order within the board; unique per starboard.", None),
    (
        "starboard_entries",
        "first_posted_at",
        "When the entry first reached the board. No code writes it, so rows created now stay null.",
        None,
    ),
    (
        "starboard_entries",
        "last_rendered_score",
        "Score the live post shows; a difference from score is what marks the entry as needing a re-render.",
        None,
    ),
    ("starboard_entries", "raw_count", "Number of voters, in either direction and unweighted.", None),
    (
        "starboard_entries",
        "score",
        "Sum of upvote weights minus downvote weights, recomputed from starboard_votes.",
        None,
    ),
    ("starboard_entries", "updated_at", "When last_rendered_score was last written.", None),
    (
        "starboard_origin_messages",
        "deleted_at",
        "Set when the source message is gone; cleared again if it turns out to still exist.",
        None,
    ),
    (
        "starboard_origin_messages",
        "posted_at",
        "When the source message was sent, against which the board's age window is measured.",
        None,
    ),
    (
        "starboard_origin_messages",
        "seen_at",
        "Last time a vote refreshed this row's copy of the message's facts.",
        None,
    ),
    ("starboard_sources", "approved_at", "When the grant was approved; set together with approved_by.", None),
    (
        "starboard_sources",
        "approved_by",
        "Discord user who approved the grant; null for grants created with the board.",
        None,
    ),
    ("starboard_sources", "channel_id", "The single source channel, or 0 for every channel in the guild.", None),
    ("starboard_votes", "direction", "'up' adds weight to the entry score, 'down' subtracts it.", None),
    (
        "starboard_votes",
        "target_author_id",
        "The origin message's author, copied here so per-author vote totals need no join.",
        None,
    ),
    (
        "starboard_votes",
        "weight",
        "Emoji multiplier times the voter's role multiplier, frozen at the time of the vote.",
        None,
    ),
    (
        "starboards",
        "channel_id",
        "The Discord channel the board posts into, not a channel it reads; sources are in starboard_sources.",
        None,
    ),
    ("starboards", "colour", "Embed accent as a packed 24-bit RGB integer.", None),
    ("starboards", "max_age_seconds", "Votes on messages older than this are rejected; 0 means no upper limit.", None),
    ("starboards", "min_age_seconds", "Votes on messages younger than this are rejected; 0 accepts any age.", None),
    ("starboards", "name", "Unique per guild, case-insensitively.", None),
    ("starboards", "required", "Weighted score at or above which an entry is posted.", None),
    (
        "starboards",
        "required_remove",
        "Weighted score at or below which a post is removed; between the two thresholds the post state is unchanged.",
        None,
    ),
    (
        "tag_aliases",
        "normalized_alias",
        "The alias case-folded and whitespace-collapsed; what lookups match against, and unique per tag.",
        None,
    ),
    ("tag_definitions", "archived_at", "Set exactly while moderation_status is 'archived'.", None),
    (
        "tag_definitions",
        "authority",
        "Member-defined tags are constrained to showcase, with no restriction type or record operator.",
        None,
    ),
    (
        "tag_definitions",
        "canonical_unit_key",
        "Unit that stored numeric values are expressed in; only ever set on numeric tags.",
        None,
    ),
    (
        "tag_definitions",
        "default_display_order",
        "Sort key for listing tags; lower sorts first, and assignments may override it.",
        None,
    ),
    (
        "tag_definitions",
        "default_display_unit_key",
        "Unit values are shown in when the assignment names none of its own.",
        None,
    ),
    ("tag_definitions", "moderation_status", "Only 'approved' tags are searchable and assignable.", None),
    (
        "tag_definitions",
        "normalized_name",
        "display_name case-folded with runs of whitespace collapsed, for duplicate detection and lookup.",
        None,
    ),
    (
        "tag_definitions",
        "numeric_step",
        "Granularity accepted for values, in the canonical unit; null on tags with no fixed granularity.",
        None,
    ),
    (
        "tag_definitions",
        "query_name",
        "Name this tag answers to in search queries; unique, and null for tags that are not searchable by name.",
        None,
    ),
    (
        "tag_definitions",
        "record_operator",
        "How a record category matches this tag; null when the tag takes part in no record category.",
        None,
    ),
    ("tag_definitions", "render_template", "Label format, with the placeholders {name}, {value} and {unit}.", None),
    ("tag_definitions", "restriction_type", "Required on restriction tags and null on every other kind.", None),
    (
        "tag_definitions",
        "stable_key",
        "Identifier code refers to instead of the id; user tags get an opaque 'user_<uuid>' carrying no submitter.",
        None,
    ),
    (
        "tag_definitions",
        "value_type",
        "Which value column an assignment of this tag fills; 'none' means the tag is a bare label.",
        None,
    ),
    ("tag_units", "aliases", "Alternative spellings accepted when parsing user input.", None),
    (
        "tag_units",
        "dimension",
        "The physical quantity measured; only units sharing a dimension are interconvertible.",
        None,
    ),
    ("tag_units", "scale_to_base", "Multiplier converting a value in this unit to its dimension's base unit.", None),
    ("tag_units", "symbol", "How the unit is rendered next to a value.", None),
    (
        "verification_codes",
        "reserved_token",
        "Digest of the token held by whoever is being shown this code's consent prompt.\n\nSays nothing about who reserved it: the prompt runs before an account exists, and the notice\npromises that cancelling stores no account information.",
        "Digest of the token held by whoever is currently being shown this code's consent prompt.\n\nA digest rather than the token, for the same reason `code` is one. Deliberately says nothing\nabout *who* reserved it: the prompt runs before an account exists, and the notice promises that\ncancelling stores no account information, so a reservation identifies nobody.",
    ),
    (
        "verification_codes",
        "reserved_until",
        "When the hold lapses, freeing the code without anything having to reap it.\n\nA crashed prompt therefore costs one hold's delay rather than a permanently stuck code.",
        "When the hold lapses, freeing the code without anything having to reap it.\n\nA crashed process therefore costs one prompt's worth of delay rather than a stuck code, and the\nlegitimate owner can always mint a fresh one from the game.",
    ),
    ("versions", "edition", "'Java' or 'Bedrock'; any other value fails to load.", None),
    (
        "vote_session_options",
        "choice",
        "How the option scores: approve adds its weight, deny subtracts it, generic only tallies.",
        None,
    ),
    (
        "vote_session_options",
        "guild_id",
        "The guild this emoji alias applies to; 0 for the alias every guild falls back to.",
        None,
    ),
    (
        "vote_session_options",
        "identifier",
        "Stable option id submitted by non-Discord surfaces, independent of the emoji.",
        None,
    ),
    (
        "vote_session_options",
        "label",
        "Display text; required for generic poll options and unset for approve/deny ones.",
        None,
    ),
    (
        "vote_session_options",
        "multiplier",
        "Finite positive factor applied to a ballot's weight when this option is picked.",
        None,
    ),
    ("vote_session_options", "position", "Display order within the session, unique per guild.", None),
    (
        "vote_sessions",
        "author_account_id",
        "The account that opened the session; it may close its own poll without any permission node.",
        None,
    ),
    (
        "vote_sessions",
        "fail_threshold",
        "Net signed vote weight at or below which the session closes as denied. NULL for generic polls.",
        None,
    ),
    (
        "vote_sessions",
        "kind",
        "What the session decides, and therefore how it closes: build, delete_log, or generic.",
        None,
    ),
    (
        "vote_sessions",
        "pass_threshold",
        "Net signed vote weight at or above which the session closes as approved. NULL for generic polls.",
        None,
    ),
    (
        "vote_sessions",
        "result",
        "The decision reached: pending until the session closes, then approved, denied, or cancelled.",
        "The result of the vote session.",
    ),
    ("vote_sessions", "status", "Whether the session still accepts ballots: open or closed.", None),
    (
        "votes",
        "guild_id",
        "The guild the ballot was cast in, which selects the option alias it matched; 0 when unknown.",
        None,
    ),
    ("votes", "option_id", "The chosen option's `vote_session_options.identifier`.", None),
    ("votes", "weight", "Finite positive magnitude; the chosen option's choice supplies the sign of the tally.", None),
    (
        "web_sessions",
        "account_id",
        "Account this session authenticates as; deleting the account deletes the session.",
        None,
    ),
    (
        "web_sessions",
        "expires_at",
        "When the session stops authenticating, set from the deployment's session TTL at creation.",
        None,
    ),
    ("web_sessions", "last_seen_at", "Stamped on every successful authentication with this session.", None),
    ("web_sessions", "revoked_at", "When logout revoked the session; null while it is still usable.", None),
    (
        "web_sessions",
        "token_hash",
        "Keyed digest of the session token, which is disclosed to the browser once and never stored.",
        None,
    ),
    (
        "web_sessions",
        "user_agent",
        "User agent that created the session, kept so a person can recognise their own sessions.",
        None,
    ),
)

_TABLE_COMMENTS: tuple[tuple[str, str | None, str | None], ...] = (
    (
        "account_merge_tickets",
        "A live, single-use claim that one account consents to being absorbed by another.\n\nA merge needs recent proof of both accounts and no session holds both, so the ticket carries the\nabsorbed side's: minting one is that side authenticating, redeeming it is the survivor's.\n\nKeyed on the account rather than the digest, so minting replaces. One live ticket per account is\nmost of why an eight-character code is enough.",
        "A live, single-use claim that one account consents to being absorbed by another.\n\nA merge needs recent proof of *both* accounts, and no one session can hold both. The ticket is\nthat second proof, carried through the only channel the two sides share: a person who can sign\ninto each. Minting one is the absorbed side authenticating; redeeming it is the surviving side\ndoing so, inside the ticket's lifetime.\n\nKeyed on the account rather than on the digest, so minting replaces. One account can only ever\nhave one live ticket, which is most of why an eight-character code is enough.",
    ),
    (
        "account_profiles",
        "What an account chooses to publish about itself on its creator page.\n\nA child of `accounts` rather than more columns on it: the account row is the identity anchor\nthat link and merge paths lock `FOR UPDATE`, and every identity read would otherwise pay for a\nbio.",
        "What an account chooses to publish about itself on its creator page.\n\nA child of `accounts` rather than more columns on it. The account row is an identity anchor\nthat thirty-odd foreign keys point at and that link and merge paths lock `FOR UPDATE`;\nprofile text is user-edited prose with an entirely different write cadence, and widening the\nanchor to carry it would make every identity read pay for a bio.",
    ),
    (
        "build_links",
        "One media URL on a build, keyed by ``(build_id, url)``, so a URL carries one media type.",
        "A link associated with a build (image, video, world download).",
    ),
    (
        "build_schematics",
        "One analyzed schematic attached to a build.\n\nUnique on `(build_id, file_sha256)`, with at most one primary row per build.\n\nMetrics and fingerprints are denormalised onto this row so duplicate shortlisting is a\nplain indexed query. Fingerprints are only comparable within the `analyzer_version` that\nproduced them, so every identity index carries that column and every lookup filters on it;\nan engine upgrade therefore becomes a visible backfill rather than a silent regression.",
        "One analyzed schematic attached to a build.\n\nMetrics and fingerprints are denormalised onto this row so duplicate shortlisting is a\nplain indexed query. Fingerprints are only comparable within the `analyzer_version` that\nproduced them, so every identity index carries that column and every lookup filters on it;\nan engine upgrade therefore becomes a visible backfill rather than a silent regression.",
    ),
    (
        "build_tag_assignments",
        "A typed tag value attached to one build; at most one row per (build, tag).",
        "A typed tag value attached to one build.",
    ),
    ("build_vote_sessions", "The build a vote session reviews, with the changes approving it would apply.", None),
    (
        "builds",
        "A build submitted by a user, and the base row of the joined-table category hierarchy.\n\n``category`` discriminates the subtype table; ``revision`` is the optimistic-lock version,\nso a write against a stale row raises SQLAlchemy's ``StaleDataError``.",
        "A build submitted by a user.",
    ),
    (
        "cli_device_enrollments",
        "One pending CLI enrollment, spent by the exchange that turns it into a device and session.",
        "A browser-approved enrollment storing only digests of bearer codes.",
    ),
    (
        "cli_devices",
        "An account-owned Ed25519 CLI device, authorized until its owner revokes it.",
        "An account-owned Ed25519 CLI device.",
    ),
    (
        "cli_session_challenges",
        "One nonce a device signs to get a session, spent by the exchange that consumes it.",
        "A one-time device proof nonce stored only as a digest.",
    ),
    (
        "cli_sessions",
        "A short-lived CLI bearer session, ended by its expiry or by revoking it or its device.",
        "A short-lived CLI bearer session storing only its token digest.",
    ),
    ("delete_log_vote_sessions", "The Discord message a vote session decides whether to delete.", None),
    (
        "discord_sync_queue",
        "A coalesced request to refresh one Discord-rendered resource; a row means its Discord posts are stale.\n\nNot an event log: at most one row exists per (resource_kind, source_key), written by the\n`INSERT ... ON CONFLICT DO UPDATE` triggers in `squid/persistence/postgres_entities.sql` and deleted on\nacknowledgement. Re-reading a row says what the resource should look like now, not what happened to it.",
        "A coalesced request to refresh one Discord-rendered resource.\n\nNot an event queue, despite the shape. Rows are coalesced on\n`(resource_kind, source_key)` by the six `INSERT ... ON CONFLICT ... DO\nUPDATE` triggers in `squid/persistence/postgres_entities.sql` — that is where\nthe coalescing actually happens — deleted on acknowledgement, and carry a\n`generation` compared against a post's applied revision as a staleness token\nrather than read as an ordering. An event log would be append-only and\nreplayable; this table is neither. A row means \"this resource's Discord posts\nare stale\", and re-reading it tells you what the resource should look like\nnow, not what happened to it.\n\nDiscord-specific on purpose: every row exists to repair a Discord post, and\nthe only consumer renders them (`squid/bot/sync/reconciler.py`). The\napplication layer speaks of *reconciliation* rather than *sync* because a\nsync names a transfer, and nothing here transfers anything.",
    ),
    (
        "domain_event_consumers",
        "A registered reader of the event log; inserting a row is what makes later events fan out to that consumer.",
        "A registered reader of the event log.",
    ),
    (
        "door_timing_variants",
        "A measured door timing variant used for lexicographic fastest records.\n\nTimes are in game ticks; NULL means the method was never measured. One row per build and\nlabel, where the label names the behaviour being timed.",
        "A measured door timing variant used for lexicographic fastest records.",
    ),
    (
        "doors",
        "A build whose category is Door: the hallway it opens and how long it takes.",
        "A door build with specific dimensions and timing information.",
    ),
    ("entrances", "A build whose category is Entrance, meaning an entrance that is not a door.", "An entrance build."),
    (
        "extender_timing_variants",
        "A measured piston-extender timing variant used for fastest records.\n\nTimes are in game ticks; NULL means the method was never measured. One row per build and\nlabel, where the label names the behaviour being timed.",
        "A measured piston-extender timing variant used for fastest records.",
    ),
    (
        "extenders",
        "A build whose category is Extender: a piston extender and how far it reaches.",
        "An extender build.",
    ),
    (
        "guild_vote_emojis",
        "One ordered emoji in a guild's preset for a session kind, snapshotted into each new session.",
        "One ordered emoji in a guild/session-kind preset.",
    ),
    (
        "guild_vote_role_weights",
        "A role multiplier scoped to one guild and session kind.\n\nA voter holding several of these votes at the highest; one holding none votes at 1.0, or at 3.0\nwith the staff weight node.",
        "A role multiplier scoped to one guild and session kind.",
    ),
    (
        "media_artifact_objects",
        "One artifact object key and its deletion state; the row outlives every artifact referencing it.",
        "Durable lifecycle and cleanup audit state for one content-addressed object.",
    ),
    (
        "media_artifact_publications",
        "One claim's lease on an object key while it writes those bytes; cleanup skips a leased key.",
        "A crash-recoverable lease protecting one claim's in-flight object publication.",
    ),
    (
        "media_artifacts",
        "One file normalization produced for an upload, at most one per role.",
        "Content-addressed normalized output, poster, or disclosure report metadata.",
    ),
    (
        "media_normalization_jobs",
        "One normalization request per upload, retained after it ends so clients can read its outcome.",
        "A retained, claim-token-fenced request to normalize one raw upload.",
    ),
    (
        "media_uploads",
        "One raw upload, described by the facts a worker re-verifies before normalizing it.\n\nEvery column but `raw_deleted_at` is immutable once written; a retry of the same id must match.",
        "Immutable raw-upload metadata used to verify worker input.",
    ),
    (
        "minecraft_paper_installations",
        "An account-owned Paper server, authenticating until its owner rotates or revokes it.",
        "An account-owned Paper installation with a non-recoverable credential.",
    ),
    (
        "minecraft_player_challenges",
        "One player authorization request, spent by the exchange that turns it into a grant.",
        "A short-lived device flow storing only hashes of both bearer codes.",
    ),
    (
        "minecraft_player_grants",
        "A short-lived player bearer grant, ended by its expiry or by revoking it or its installation.",
        "A short-lived origin- and identity-bound player bearer grant.",
    ),
    (
        "notification_profiles",
        "Per-account channel switches. Consent lives on `accounts`; a row here does not imply the notice was accepted.",
        'Independent notification channel preferences.\n\nCarries no consent receipt: notifications are covered by the one privacy notice, whose\nreceipt lives on `accounts`. A row here means "these switches", not "this person agreed".',
    ),
    (
        "notification_subscriptions",
        "One standing subscription, to a creator, an exact record, or a structured record filter.",
        "A creator, exact record, or structured record-filter subscription.",
    ),
    (
        "notifications",
        "One inbox item; the unique `source_key` makes re-materializing an event a no-op.",
        "An idempotently materialized user notification.",
    ),
    (
        "oauth_states",
        "One-time OAuth PKCE state shared across API replicas; the callback deletes the row it reads.",
        "One-time OAuth PKCE state shared across API replicas.",
    ),
    (
        "permission_role_patterns",
        "One pattern a role includes or subtracts.\n\nSubtraction is not a deny: it withholds the pattern from this role's contribution only, and\nany other role including it still confers it. These are Azure's `NotActions` semantics.",
        "One pattern a role includes or subtracts.\n\nSubtraction is not a deny: it withholds the pattern from *this* role's\ncontribution, and any other role including it still confers it. That is\nAzure's `NotActions` semantics, and it is why a role can be written as \"this\nnamespace, minus its destructive members\" without poisoning other grants.",
    ),
    (
        "schematic_files",
        "Relational metadata for a content-addressed schematic artifact.\n\nOne row per distinct file, shared by every build that uploaded those exact bytes. The payload\nitself lives in object storage under `object_key`.",
        "Relational metadata for a content-addressed schematic artifact.",
    ),
    (
        "schematic_jobs",
        "A durable request for the worker-owned native schematic engine.\n\nThe one queue whose rows outlive their acknowledgement: a client polls this row for its result\nuntil `expires_at` passes and cleanup deletes it. `completed_at` and `dead_at` are mutually\nexclusive, and either one means the row is no longer claimable.",
        "A durable request for the worker-owned native schematic engine.",
    ),
    (
        "schematic_render_queue",
        "A durable request to render and publish one build's primary schematic.\n\nKeyed by build, so re-attaching a primary schematic resets the existing row rather than\nqueueing a second render.",
        "A durable request to render and publish one build's primary schematic.",
    ),
    (
        "schematic_renders",
        "A replaceable preview artifact keyed by the complete rendering recipe.\n\nUnique on `(build_schematic_id, recipe_hash)`: one stored image per attachment per recipe, and\na changed pack, camera, size, or analyzer version is a different recipe rather than an update.",
        "A replaceable preview artifact keyed by the complete rendering recipe.",
    ),
    (
        "search_document_facets",
        "A typed, indexed field value belonging to a search document.\n\nExactly one of the four value columns is non-NULL, and its type decides which comparisons the\nfield supports.",
        "A typed, indexed field value belonging to a search document.",
    ),
    (
        "search_documents",
        "An indexed projection of a searchable application resource.\n\nOne row per `(resource_kind, source_key)`; every column is derived, so the row is rewritten\nwholesale whenever the source changes.",
        "An indexed projection of a searchable application resource.",
    ),
    (
        "search_embedding_queue",
        "A durable request to embed a search document whose source hash changed.\n\nOne row per document, re-armed whenever the document's content hash changes.",
        "A durable request to embed a search document whose source hash changed.",
    ),
    (
        "server_settings",
        "One Discord guild's configuration; the row outlives the bot's membership of the guild.",
        "Settings for a Discord server.",
    ),
    (
        "starboard_entries",
        "The current score of one source message on one starboard, and what its post last showed.",
        "The materialized-post state for one source message on one starboard.",
    ),
    (
        "starboard_origin_messages",
        "A source message a starboard has evaluated; the id is the Discord message id.",
        "A source message that has been evaluated by at least one starboard.",
    ),
    (
        "starboard_role_multipliers",
        "The weight a Discord role gives its members' votes on one starboard; roles with no row weigh 1.",
        "A role multiplier scoped to one starboard.",
    ),
    (
        "starboard_sources",
        "A grant letting one channel's messages, or a whole guild's, feed a starboard.",
        "A guild or channel whose messages feed a starboard.",
    ),
    (
        "submission_draft_access",
        "An account's role on a draft; a partial unique index allows exactly one owner per draft.",
        "An account's role on a draft; v1 creates exactly one owner grant.",
    ),
    (
        "tag_aliases",
        "An alternate name a tag is recognized by when parsing input.",
        "An alternate display name for a tag.",
    ),
    (
        "tag_applicabilities",
        "A build kind a tag may be used on; a tag with no rows here is unrestricted.",
        "A build kind on which a tag may be used.",
    ),
    (
        "tag_record_thresholds",
        "A staff-seeded value of a numeric restriction that records are tracked at.",
        "A staff-seeded eager threshold for a parameterized restriction.",
    ),
    (
        "tag_relations",
        "A directed relation between two tags: the source implies the target, or the two are incompatible.",
        "A semantic relationship between official restrictions.",
    ),
    ("utilities", "A build whose category is Utility; it carries no category-specific columns.", "A utility build."),
    (
        "verification_attempts",
        "Consecutive failed code redemptions for one external identity.\n\nKeyed on `(provider, subject)` with no foreign key, because the guesser may not have an account\nyet. The counter is consecutive: a success clears it.",
        "Consecutive failed code redemptions for one external identity.\n\nKeyed on `(provider, subject)` rather than on an account, because the guesser may not have an\naccount yet: a redemption is the first thing many callers ever do, and creating a row for\nsomeone in order to rate-limit them would defeat the point. No foreign key for the same reason.\n\nThe counter is *consecutive*: a success clears it, so an honest user who mistypes twice and then\ngets it right is never closer to a lockout than someone who never failed.",
    ),
    (
        "versions",
        "One released Minecraft version that builds may declare compatibility with.",
        "A version of Minecraft that a build is compatible with.",
    ),
    (
        "votes",
        "One account's current ballot in a vote session; withdrawing it deletes the row.",
        "A vote cast in a vote session.",
    ),
    (
        "web_sessions",
        "A revocable opaque browser session, valid until it expires or is revoked.",
        "A revocable opaque browser session.",
    ),
)


def upgrade() -> None:
    for table, column, new, old in _COLUMN_COMMENTS:
        op.alter_column(table, column, comment=new, existing_comment=old)
    for table, new, old in _TABLE_COMMENTS:
        if new is None:
            op.drop_table_comment(table, existing_comment=old)
        else:
            op.create_table_comment(table, new, existing_comment=old)


def downgrade() -> None:
    for table, column, new, old in _COLUMN_COMMENTS:
        op.alter_column(table, column, comment=old, existing_comment=new)
    for table, new, old in _TABLE_COMMENTS:
        if old is None:
            op.drop_table_comment(table, existing_comment=new)
        else:
            op.create_table_comment(table, old, existing_comment=new)
