"""document database tables

Revision ID: 7a40995322dc
Revises: 20260728_vote_options
Create Date: 2026-07-28 22:10:19.466225
"""

from collections.abc import Sequence

from alembic import op

revision: str = "7a40995322dc"
down_revision: str | Sequence[str] | None = "20260728_vote_options"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "build_creators", "Association table between builds and their creators.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "build_edit_history", "A version marker recorded when a build is edited.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "build_links",
        "A link associated with a build (image, video, world download).",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment(
        "build_restrictions",
        "Association table between builds and their restrictions.",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment(
        "build_types", "Association table between builds and their types.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "build_versions", "Association table between builds and their versions.", existing_comment=None, schema=None
    )
    op.create_table_comment("builds", "A build submitted by a user.", existing_comment=None, schema=None)
    op.create_table_comment(
        "messages", "A message associated with a build or vote session.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "restriction_aliases",
        "An alias for a restriction, allowing for alternative names.",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment(
        "restrictions", "A restriction that can be applied to builds.", existing_comment=None, schema=None
    )
    op.create_table_comment("server_settings", "Settings for a Discord server.", existing_comment=None, schema=None)
    op.create_table_comment(
        "smallest_door_records",
        "A door that is the smallest in a specific category.\n\nThis table is a cache for the smallest doors in each category up to 8 restrictions, built by using database triggers",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment("types", "A build pattern.", existing_comment=None, schema=None)
    op.create_table_comment(
        "users",
        "A user in the system, which can be linked to both Discord and Minecraft accounts.",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment(
        "verification_codes", "A verification code for linking Minecraft accounts.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "versions", "A version of Minecraft that a build is compatible with.", existing_comment=None, schema=None
    )
    op.create_table_comment(
        "vote_sessions", "A voting session for builds or log deletions.", existing_comment=None, schema=None
    )
    op.create_table_comment("votes", "A vote cast in a vote session.", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision when the operation is safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("votes", existing_comment="A vote cast in a vote session.", schema=None)
    op.drop_table_comment(
        "vote_sessions", existing_comment="A voting session for builds or log deletions.", schema=None
    )
    op.drop_table_comment(
        "versions", existing_comment="A version of Minecraft that a build is compatible with.", schema=None
    )
    op.drop_table_comment(
        "verification_codes", existing_comment="A verification code for linking Minecraft accounts.", schema=None
    )
    op.drop_table_comment(
        "users",
        existing_comment="A user in the system, which can be linked to both Discord and Minecraft accounts.",
        schema=None,
    )
    op.drop_table_comment("types", existing_comment="A build pattern.", schema=None)
    op.drop_table_comment(
        "smallest_door_records",
        existing_comment="A door that is the smallest in a specific category.\n\nThis table is a cache for the smallest doors in each category up to 8 restrictions, built by using database triggers",
        schema=None,
    )
    op.drop_table_comment("server_settings", existing_comment="Settings for a Discord server.", schema=None)
    op.drop_table_comment("restrictions", existing_comment="A restriction that can be applied to builds.", schema=None)
    op.drop_table_comment(
        "restriction_aliases",
        existing_comment="An alias for a restriction, allowing for alternative names.",
        schema=None,
    )
    op.drop_table_comment(
        "messages", existing_comment="A message associated with a build or vote session.", schema=None
    )
    op.drop_table_comment("builds", existing_comment="A build submitted by a user.", schema=None)
    op.drop_table_comment(
        "build_versions", existing_comment="Association table between builds and their versions.", schema=None
    )
    op.drop_table_comment(
        "build_types", existing_comment="Association table between builds and their types.", schema=None
    )
    op.drop_table_comment(
        "build_restrictions", existing_comment="Association table between builds and their restrictions.", schema=None
    )
    op.drop_table_comment(
        "build_links", existing_comment="A link associated with a build (image, video, world download).", schema=None
    )
    op.drop_table_comment(
        "build_edit_history", existing_comment="A version marker recorded when a build is edited.", schema=None
    )
    op.drop_table_comment(
        "build_creators", existing_comment="Association table between builds and their creators.", schema=None
    )
    # ### end Alembic commands ###
