"""Drop the unusable build_edit_history table

`build_edit_history` was meant to record a version marker each time a build is edited. It cannot,
and never could, for three independent reasons:

- `build_id` was the sole primary key, so the table holds at most one row per build. A history
  table that cannot hold two rows for the same subject is not a history table.
- `unique_version_per_build UNIQUE (build_id, version)` was therefore already implied by the
  primary key, and constrained nothing.
- `build_id` also carried `GENERATED BY DEFAULT AS IDENTITY` while being a foreign key into
  `builds.id`, so a row inserted without an explicit build id would have been filed under a
  sequence number rather than under the build that was edited.

No code has ever written to it -- `BuildEditHistory` was referenced nowhere outside its own class
statement -- so it is empty, and dropping it loses nothing. Build revisions are tracked by
`builds.revision` and, since `d4e5f6a7b8c9`, by the build-revision projection; whatever replaces
this table should be designed against those rather than resurrected from this shape.

Revision ID: e6a0b3d8c592
Revises: d5f9a2c7b481
Create Date: 2026-08-17 12:10:00.000000+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e6a0b3d8c592"
down_revision: str | Sequence[str] | None = "d5f9a2c7b481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.drop_table("build_edit_history")


def downgrade() -> None:
    """Revert this revision."""
    # Recreated exactly as it was, identity and redundant unique constraint included, so that
    # downgrading lands on the schema this revision was applied to rather than on a repaired
    # version of it that no migration ever produced.
    op.create_table(
        "build_edit_history",
        sa.Column("build_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("build_id", name="build_edit_history_pkey"),
        sa.UniqueConstraint("build_id", "version", name="unique_version_per_build"),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
            name="build_edit_history_build_id_fkey",
            ondelete="CASCADE",
            onupdate="CASCADE",
        ),
        comment="A version marker recorded when a build is edited.",
    )
