"""Semantic-first, limits-aware UI planning and component runtime."""

from importlib import import_module
from typing import TYPE_CHECKING

from squid_reactivity.operations import operation
from squid_ui import (
    errors,
    forms,
    guards,
    html,
    interactions,
    operations,
    planning,
    primitives,
    profiling,
    resources,
    routing,
    runtime,
    scene,
    semantic,
    slack,
    sources,
    temporal,
    text,
)

# These deeper-tier namespaces are part of the root API, but importing chrome before runtime
# completes resurrects a partial-initialization cycle. Bind them explicitly after the namespace
# bundle is ready; the type-checking imports make their module surfaces visible statically.
if TYPE_CHECKING:
    import squid_ui.chrome as chrome
    import squid_ui.document as document
    import squid_ui.emoji as emoji
    import squid_ui.entity as entity
    import squid_ui.palette as palette
else:
    chrome = import_module("squid_ui.chrome")
    document = import_module("squid_ui.document")
    emoji = import_module("squid_ui.emoji")
    entity = import_module("squid_ui.entity")
    palette = import_module("squid_ui.palette")

from squid_ui.document import (
    Document,
    DocumentLike,
)
from squid_ui.errors import (
    DrawInvariantError,
    ExistingLayoutError,
    LayoutDegradedError,
    LayoutError,
    LayoutInvariantError,
    LimitViolationError,
    SquidUiError,
    UnsolvableLayoutError,
)
from squid_ui.factories import (
    ChildLike,
    Conditional,
    TextValue,
    action_control,
    action_controls,
    article,
    aside,
    block,
    bullet,
    bullets,
    choice,
    choices,
    cluster,
    code,
    column,
    columns,
    control_group,
    controlled,
    details,
    download,
    entities,
    entity_choice,
    field,
    fields,
    figure,
    form,
    grid,
    group,
    heading,
    item,
    item_label,
    items,
    link,
    media,
    media_item,
    metric,
    nav_option,
    navigation,
    note,
    paragraph,
    progress,
    quote,
    rating,
    roster,
    routed_action_control,
    routed_choices,
    section,
    stack,
    status,
    summary,
    table,
    table_row,
    tally,
    themed,
    timestamp,
    toggle,
    uncontrolled,
    zoned_timestamp,
)
from squid_ui.interactions import (
    ActionEvent,
    EntitySelectionEvent,
    PressEvent,
    SelectionEvent,
    SubmitEvent,
)
from squid_ui.palette import Palette, PaletteRegistry
from squid_ui.runtime.component import Component
from squid_ui.runtime.context import ContextKey
from squid_ui.runtime.reactivity import (
    computed,
    state,
)
from squid_ui.runtime.resources import resource
from squid_ui.semantic import (
    ChoiceEvent,
    EntityEvent,
    LayoutNode,
    NavigateEvent,
    OpenEvent,
    ScaleEvent,
    ToggleEvent,
    Tone,
    best_effort,
    budget,
    fallback,
    keep_with_next,
    optional,
    paged,
    spill,
    truncate,
    unbreakable,
)
from squid_ui.target_types import (
    ClassicTarget,
    ComponentsV2Target,
    DiscordTarget,
    HtmlTarget,
    Renderable,
    RenderTarget,
    SlackHomeTarget,
    SlackMessageTarget,
    SlackModalTarget,
    SlackTarget,
)
from squid_ui.text import (
    TextLike,
    md,
    plain,
    raw_md,
)

__all__ = [
    "ActionEvent",
    "ChildLike",
    "ChoiceEvent",
    "ClassicTarget",
    "Component",
    "ComponentsV2Target",
    "Conditional",
    "ContextKey",
    "DiscordTarget",
    "Document",
    "DocumentLike",
    "DrawInvariantError",
    "EntityEvent",
    "EntitySelectionEvent",
    "ExistingLayoutError",
    "HtmlTarget",
    "LayoutDegradedError",
    "LayoutError",
    "LayoutInvariantError",
    "LayoutNode",
    "LimitViolationError",
    "NavigateEvent",
    "OpenEvent",
    "Palette",
    "PaletteRegistry",
    "PressEvent",
    "RenderTarget",
    "Renderable",
    "ScaleEvent",
    "SelectionEvent",
    "SlackHomeTarget",
    "SlackMessageTarget",
    "SlackModalTarget",
    "SlackTarget",
    "SquidUiError",
    "SubmitEvent",
    "TextLike",
    "TextValue",
    "ToggleEvent",
    "Tone",
    "UnsolvableLayoutError",
    "action_control",
    "action_controls",
    "article",
    "aside",
    "best_effort",
    "block",
    "budget",
    "bullet",
    "bullets",
    "choice",
    "choices",
    "cluster",
    "code",
    "column",
    "columns",
    "computed",
    "control_group",
    "controlled",
    "details",
    "download",
    "entities",
    "entity_choice",
    "errors",
    "fallback",
    "field",
    "fields",
    "figure",
    "form",
    "forms",
    "grid",
    "group",
    "guards",
    "heading",
    "html",
    "interactions",
    "item",
    "item_label",
    "items",
    "keep_with_next",
    "link",
    "md",
    "media",
    "media_item",
    "metric",
    "nav_option",
    "navigation",
    "note",
    "operation",
    "operations",
    "optional",
    "paged",
    "paragraph",
    "plain",
    "planning",
    "primitives",
    "profiling",
    "progress",
    "quote",
    "rating",
    "raw_md",
    "resource",
    "resources",
    "roster",
    "routed_action_control",
    "routed_choices",
    "routing",
    "runtime",
    "scene",
    "section",
    "semantic",
    "slack",
    "sources",
    "spill",
    "stack",
    "state",
    "status",
    "summary",
    "table",
    "table_row",
    "tally",
    "temporal",
    "text",
    "themed",
    "timestamp",
    "toggle",
    "truncate",
    "unbreakable",
    "uncontrolled",
    "zoned_timestamp",
]
