"""Public voting domain API."""

from squid.voting.domain.models import (
    DEFAULT_GENERIC_EMOJIS,
    DEFAULT_VOTE_OPTIONS,
    CastVoteResult,
    EmojiPreset,
    GenericPoll,
    RoleWeight,
    StoredVoteMutation,
    VoteActor,
    VoteChange,
    VoteChoice,
    VoteChoiceLiteral,
    VoteKindLiteral,
    VoteMessage,
    VoteOption,
    VoteRefreshResult,
    VoteRejection,
    VoteSelection,
    VoteSessionResultLiteral,
    VoteSessionSnapshot,
    VoteStatus,
    VoteTarget,
    VoteVisibility,
    normalize_vote_options,
)

__all__ = [
    "DEFAULT_GENERIC_EMOJIS",
    "DEFAULT_VOTE_OPTIONS",
    "CastVoteResult",
    "EmojiPreset",
    "GenericPoll",
    "RoleWeight",
    "StoredVoteMutation",
    "VoteActor",
    "VoteChange",
    "VoteChoice",
    "VoteChoiceLiteral",
    "VoteKindLiteral",
    "VoteMessage",
    "VoteOption",
    "VoteRefreshResult",
    "VoteRejection",
    "VoteSelection",
    "VoteSessionResultLiteral",
    "VoteSessionSnapshot",
    "VoteStatus",
    "VoteTarget",
    "VoteVisibility",
    "normalize_vote_options",
]
