"""Backend-neutral replicated engine and staging contracts."""

from typing import Any, Protocol

from squid_reactivity import ConflictDetail


class ReplicaBranch[SnapshotT, OperationT, PreparedT](Protocol):
    """An isolated branch whose prepared work has not changed canonical state."""

    def apply(self, operation: OperationT) -> None: ...

    def snapshot(self) -> SnapshotT: ...

    def prepare(self, base: object) -> PreparedT: ...

    def stage_inverse(self, inverse: object) -> None: ...

    @property
    def base(self) -> object: ...

    @property
    def operations(self) -> tuple[OperationT, ...]: ...


class ReplicationEngine[SnapshotT, OperationT, PreparedT, ChangeT](Protocol):
    """A CRDT backend hidden behind immutable snapshots and opaque causal tokens."""

    @property
    def backend_id(self) -> str: ...

    @property
    def replica_id(self) -> str: ...

    @property
    def container_kinds(self) -> frozenset[str]: ...

    def snapshot(self) -> SnapshotT: ...

    def version(self) -> object: ...

    def branch(self) -> ReplicaBranch[SnapshotT, OperationT, PreparedT]: ...

    def apply(self, prepared: PreparedT) -> ChangeT: ...

    def prepare_remote(self, update: bytes) -> PreparedT: ...

    def export_since(self, version: object | None = None) -> bytes: ...

    def change_token(self, prepared: PreparedT) -> object | None: ...

    def encode_token(self, token: object) -> bytes: ...

    def decode_token(self, token: bytes) -> object: ...

    def plan_inverse(self, token: object) -> object | ConflictDetail: ...

    def encode_prepared(self, prepared: PreparedT) -> bytes: ...

    def make_operation(self, kind: str, path: str, **data: Any) -> OperationT: ...

    def visible_tags(
        self,
        path: str,
        value: str,
        additions: tuple[OperationT, ...] = (),
    ) -> tuple[object, ...]: ...

    def retain_token(self, token: object) -> object: ...

    def release_token(self, retention: object) -> None: ...

    def compact(self) -> None: ...


class ReplicationBackend(Protocol):
    """A configured engine factory reusable for every document in one replica."""

    @property
    def backend_id(self) -> str: ...

    def open_engine(
        self,
        replica_id: str,
        document_id: str,
    ) -> Any: ...
