[package]
name = "squid-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "squid"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde_json.workspace = true
squid-cli-core.workspace = true

[lints]
workspace = true
