"""Permission domain values: the node catalogue, patterns, and resolution."""

from squid.permissions.domain.catalogue import (
    BUILTIN_ROLES,
    BUILTIN_ROLES_BY_KEY,
    CATALOGUE,
    BuiltinRoleKeys,
    Catalogue,
    CatalogueBuilder,
    RoleDefinition,
)
from squid.permissions.domain.matching import Pattern, Specificity
from squid.permissions.domain.models import (
    CatalogueError,
    Default,
    Effect,
    GlobalAdministrator,
    InvalidPatternError,
    NodeScope,
    PermissionNode,
    Tag,
    UnknownPermissionNodeError,
)
from squid.permissions.domain.resolution import (
    MAX_ROLE_DEPTH,
    Decision,
    Origin,
    Reason,
    RoleExpansion,
    RoleSpec,
    Rule,
    Subject,
    SubjectKind,
    TraceStep,
    allows,
    expand_role,
    resolve,
    resolve_many,
    rules_from_role,
)

__all__ = [
    "BUILTIN_ROLES",
    "BUILTIN_ROLES_BY_KEY",
    "CATALOGUE",
    "MAX_ROLE_DEPTH",
    "BuiltinRoleKeys",
    "Catalogue",
    "CatalogueBuilder",
    "CatalogueError",
    "Decision",
    "Default",
    "Effect",
    "GlobalAdministrator",
    "InvalidPatternError",
    "NodeScope",
    "Origin",
    "Pattern",
    "PermissionNode",
    "Reason",
    "RoleDefinition",
    "RoleExpansion",
    "RoleSpec",
    "Rule",
    "Specificity",
    "Subject",
    "SubjectKind",
    "Tag",
    "TraceStep",
    "UnknownPermissionNodeError",
    "allows",
    "expand_role",
    "resolve",
    "resolve_many",
    "rules_from_role",
]
