#!/bin/sh
#!/usr/bin/env bash

exit=0
echo "Running ruff check..."
if ! ruff check --extend-select I --fix
then
    exit=1
fi

echo "Running ruff format..."
if ! ruff format --check --target-version py312 --quiet
then
    exit=1
    ruff format --target-version py312
fi

if [ $exit -ne 0 ]
then
    echo "ruff checks or formatting failed."
    exit 1
fi

echo "ruff checks and formatting completed successfully."