[versions]
brigadier = "1.3.10"
fabric-api = "0.149.1+26.1.2"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"
fabric-loader = "0.19.3"
fabric-loom = "1.17.19"
junit = "5.13.4"
kotlin = "2.4.10"
kotlinx-serialization = "1.11.0"
minecraft = "26.1.2"
paper = "26.1.2.build.74-stable"
shadow = "9.6.1"

[libraries]
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
