ALTER TABLE builds
ALTER COLUMN information SET DEFAULT '{}'::jsonb,
ALTER COLUMN information SET NOT NULL,
ALTER COLUMN width DROP NOT NULL,
ALTER COLUMN height DROP NOT NULL,
ALTER COLUMN depth DROP NOT NULL;