-- Add title column to builds table
-- This column will store the generated title from build.get_title() method
alter table "public"."builds" add column "title" text;

-- Add comment explaining the purpose of the title column
comment on column "public"."builds"."title" is 'The official Redstone Squid defined title for the build, generated by build.get_title() method'; 