CREATE TABLE public.restriction_aliases (
  restriction_id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  alias TEXT NOT NULL UNIQUE,
  CONSTRAINT restriction_aliases_pkey PRIMARY KEY (alias),
  CONSTRAINT restriction_aliases_restriction_id_fkey
    FOREIGN KEY (restriction_id) REFERENCES public.restrictions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- Index on restriction_id
CREATE INDEX restriction_aliases_restriction_id_idx
  ON public.restriction_aliases (restriction_id);

-- Validate the foreign key constraint
ALTER TABLE public.restriction_aliases
  VALIDATE CONSTRAINT restriction_aliases_restriction_id_fkey;

-- Enable row-level security
ALTER TABLE public.restriction_aliases ENABLE ROW LEVEL SECURITY;

grant delete on table "public"."restriction_aliases" to "anon";
grant insert on table "public"."restriction_aliases" to "anon";
grant references on table "public"."restriction_aliases" to "anon";
grant select on table "public"."restriction_aliases" to "anon";
grant trigger on table "public"."restriction_aliases" to "anon";
grant truncate on table "public"."restriction_aliases" to "anon";
grant update on table "public"."restriction_aliases" to "anon";
grant delete on table "public"."restriction_aliases" to "authenticated";
grant insert on table "public"."restriction_aliases" to "authenticated";
grant references on table "public"."restriction_aliases" to "authenticated";
grant select on table "public"."restriction_aliases" to "authenticated";
grant trigger on table "public"."restriction_aliases" to "authenticated";
grant truncate on table "public"."restriction_aliases" to "authenticated";
grant update on table "public"."restriction_aliases" to "authenticated";
grant delete on table "public"."restriction_aliases" to "service_role";
grant insert on table "public"."restriction_aliases" to "service_role";
grant references on table "public"."restriction_aliases" to "service_role";
grant select on table "public"."restriction_aliases" to "service_role";
grant trigger on table "public"."restriction_aliases" to "service_role";
grant truncate on table "public"."restriction_aliases" to "service_role";
grant update on table "public"."restriction_aliases" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."restriction_aliases"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable read access for all users"
on "public"."restriction_aliases"
as permissive
for select
to public
using (true);
